"use client";
import Link from "next/link";
import { Eye, Megaphone, MoreHorizontal, Plus, Search, Target, WalletCards } from "lucide-react";
import { AdminPageTitle } from "../shared/admin-page-title";
import { ChannelLogo } from "../shared/channel-logo";
import { useCampaigns } from "../shared/use-admin-workspace";
import { cn } from "@/lib/utils/cn";
export function CampaignsPage() { const { data = [] } = useCampaigns(); return <div className="space-y-3"><AdminPageTitle eyebrow="Marketing / Campaigns" title="Campaigns" description="Plan and measure cross-channel campaigns for Moksha Sewa." action={<button className="flex h-8 items-center gap-1.5 rounded-lg bg-[#EB0711] px-3 text-[9px] font-semibold text-white"><Plus className="size-3.5" />Create Campaign</button>} /><div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Metric icon={Megaphone} label="Total Campaigns" value="4" /><Metric icon={Target} label="Campaign Leads" value="426" /><Metric icon={WalletCards} label="Total Spend" value="₹53.6K" /><Metric icon={Eye} label="Conversions" value="109" /></div><section className="overflow-hidden rounded-lg border border-[#DDE4ED] bg-white shadow-sm"><div className="flex items-center border-b border-[#E8EDF3] p-2.5"><label className="flex h-8 max-w-[360px] flex-1 items-center gap-2 rounded-lg border border-[#DDE4ED] bg-[#F8FAFD] px-3"><Search className="size-3 text-[#71809D]" /><input className="w-full bg-transparent text-[8.5px] outline-none" placeholder="Search campaigns..." /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-[#F8FAFD] text-[7px] uppercase tracking-wider text-[#75829D]"><tr>{["Campaign", "Channels", "Status", "Duration", "Leads", "Spend", "Conversions", ""].map((item) => <th key={item} className="px-3 py-2 font-semibold">{item}</th>)}</tr></thead><tbody className="divide-y divide-[#E8EDF3]">{data.map((campaign) => <tr key={campaign.id} className="text-[8.5px] hover:bg-[#FBFCFE]"><td className="px-3 py-2.5"><Link href={`/admin/campaigns/${campaign.id}`} className="font-bold text-[#172044] hover:text-[#EB0711]">{campaign.name}</Link><p className="text-[7.5px] text-[#75829D]">{campaign.project}</p></td><td className="px-3"><div className="flex gap-1">{campaign.channels.map((channel) => <ChannelLogo key={channel} channel={channel} className="size-5" />)}</div></td><td className="px-3"><span className={cn("rounded-full px-2 py-1 text-[7px] font-semibold", campaign.status === "Active" ? "bg-[#E5F7EF] text-[#078359]" : campaign.status === "Completed" ? "bg-[#EAF2FF] text-[#286CB7]" : "bg-[#F1F3F7] text-[#65738D]")}>{campaign.status}</span></td><td className="px-3 text-[#586986]">{campaign.startDate} – {campaign.endDate}</td><td className="px-3 font-bold">{campaign.leads}</td><td className="px-3">₹{campaign.spend.toLocaleString()}</td><td className="px-3 font-bold text-[#078359]">{campaign.conversions}</td><td className="px-3"><button className="grid size-7 place-items-center rounded-md hover:bg-[#EEF2F7]"><MoreHorizontal className="size-3.5" /></button></td></tr>)}</tbody></table></div></section></div>; }
function Metric({ icon: Icon, label, value }: { icon: typeof Megaphone; label: string; value: string }) { return <div className="rounded-lg border border-[#DDE4ED] bg-white p-2.5 shadow-sm"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-[#FFF0F1] text-[#EB0711]"><Icon className="size-3.5" /></span><div><p className="text-[7.5px] text-[#75829D]">{label}</p><p className="text-[17px] font-bold text-[#172044]">{value}</p></div></div></div>; }
