process.env.NEXT_PUBLIC_MOCK_LATENCY_MS = "0";
const { auditRepository: repo } = await import("../data/repository");
const { resolveWindow } = await import("../data/filters");
const { platformNow } = await import("@/features/companies/data/clock");
const w = resolveWindow("30d", platformNow());
const page = await repo.listEvents({ window: { from: "2000-01-01T00:00:00Z", to: "2100-01-01T00:00:00Z" }, pageSize: 5000 });
console.log("ALL", page.total);
const p30 = await repo.listEvents({ window: w, pageSize: 5000 });
console.log("30d", p30.total, "24h", (await repo.listEvents({ window: resolveWindow("24h", platformNow()), pageSize: 5000 })).total, "7d", (await repo.listEvents({ window: resolveWindow("7d", platformNow()), pageSize: 5000 })).total);
const by: Record<string, number> = {};
for (const e of page.rows) by[e.sourceModule + "|" + e.category] = (by[e.sourceModule + "|" + e.category] ?? 0) + 1;
console.log(JSON.stringify(by));
const ov = await repo.getOverview(w, null);
console.log(JSON.stringify(ov.kpis), ov.categories.length, ov.attention.length, ov.recentSensitive.length);
const ids = new Set(page.rows.map((e) => e.id));
console.log("unique ids", ids.size === page.rows.length);
const inv = await repo.listInvestigations({});
console.log(JSON.stringify(inv.counts), inv.rows.map((r) => r.investigation.id + ":" + r.linkedEvents).join(","));
const wf = page.rows.filter((e) => e.correlationId).reduce<Record<string, number>>((m, e) => { m[e.correlationId!] = (m[e.correlationId!] ?? 0) + 1; return m; }, {});
console.log("multi-event workflows", Object.entries(wf).filter(([, n]) => n > 1).length);
console.log(JSON.stringify(page.rows.find((e) => e.actionKey === "feature_flag.emergency_disabled")?.id));
