import { AllSettingsState, SettingsCapabilities } from "./types";

export const INITIAL_SETTINGS_STATE: AllSettingsState = {
  organization: {
    name: "Namo Gange Trust",
    legalName: "Namo Gange Public Charitable Trust",
    displayName: "Namo Gange",
    industry: "Healthcare, Ayurveda & Non-Profit",
    website: "https://namogange.org",
    contactEmail: "contact@namogange.org",
    contactPhone: "+91 98765 43210",
    logo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=200&q=80",
    description:
      "A national non-profit organization promoting traditional Indian medicine, Ayurveda research, holistic healthcare education, and community social wellness campaigns.",
    address: {
      country: "India",
      state: "Delhi",
      city: "New Delhi",
      address: "12/4, Institutional Area, Lodhi Road",
      pinCode: "110003",
    },
    metadata: {
      id: "org_namogange_9942a",
      createdAt: "Jan 12, 2024",
      owner: "Manish Sirohi",
      ownerEmail: "manishsirohi@encodency.com",
      currentPlan: "Enterprise Organization Tier",
      planStatus: "Active",
      totalMembers: 12,
      totalClients: 4,
    },
  },
  workspace: {
    primaryClient: "Moksha Sewa",
    defaultClientAfterLogin: "Moksha Sewa",
    rememberLastSelectedClient: true,
    defaultWorkspaceLandingPage: "Dashboard",
    defaultDateRange: "Last 30 days",
    resetFiltersOnClientSwitch: false,
    rememberFiltersPerClient: true,
    clearLocalWorkspaceState: false,
  },
  branding: {
    logo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=200&q=80",
    favicon: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=64&q=80",
    brandName: "Namo Gange",
    primaryColor: "#10B981",
    secondaryColor: "#111C3A",
    reportLogo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=200&q=80",
    emailLogo: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=200&q=80",
    footerText: "© 2026 Namo Gange Trust. Powered by EnCodency OmniPlatform.",
    customDomain: "portal.namogange.org",
    isWhiteLabelEnabled: false,
  },
  notifications: [
    // Operational
    {
      id: "notif_auto_fail",
      title: "Automation Failure",
      description: "Triggered whenever an automated workflow or inbound webhook execution fails or exceeds retry limit.",
      category: "operational",
      inApp: true,
      email: true,
      whatsapp: true,
      slack: true,
    },
    {
      id: "notif_integ_alert",
      title: "Integration Needs Attention",
      description: "When an active social or messaging channel token expires, is revoked, or hits a rate limit.",
      category: "operational",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: true,
    },
    {
      id: "notif_site_down",
      title: "Website Down Alert",
      description: "Instant notification when uptime monitor detects downtime or 5xx server errors on monitored sites.",
      category: "operational",
      inApp: true,
      email: true,
      whatsapp: true,
      slack: true,
    },
    {
      id: "notif_seo_crit",
      title: "SEO Critical Issue Detected",
      description: "When indexing drops, Core Web Vitals degrade, or critical search console errors occur.",
      category: "operational",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: false,
    },
    {
      id: "notif_post_fail",
      title: "Failed Scheduled Post",
      description: "When an scheduled campaign social post fails to publish to LinkedIn, Meta, or YouTube.",
      category: "operational",
      inApp: true,
      email: false,
      whatsapp: true,
      slack: true,
    },
    // Collaboration
    {
      id: "notif_task_assign",
      title: "Task Assigned",
      description: "When a team member or manager assigns a content review or campaign task to you.",
      category: "collaboration",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: true,
    },
    {
      id: "notif_appr_req",
      title: "Approval Requested",
      description: "When a content creator submits media assets or post copies requiring administrative sign-off.",
      category: "collaboration",
      inApp: true,
      email: true,
      whatsapp: true,
      slack: true,
    },
    {
      id: "notif_appr_comp",
      title: "Approval Completed",
      description: "When an asset, campaign post, or budget request is officially approved or rejected.",
      category: "collaboration",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: false,
    },
    {
      id: "notif_mention",
      title: "Mention Received (@)",
      description: "When someone mentions your name or group handle in campaign comments or internal notes.",
      category: "collaboration",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: true,
    },
    // Account
    {
      id: "notif_member_join",
      title: "Team Member Joined",
      description: "When an invited colleague accepts their organization invitation and completes onboarding.",
      category: "account",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: true,
    },
    {
      id: "notif_role_change",
      title: "Role & Permission Changed",
      description: "When an administrator modifies team roles, privilege sets, or client access scopes.",
      category: "account",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: true,
    },
    {
      id: "notif_sec_alert",
      title: "Security & Policy Alert",
      description: "Unrecognized login location, suspicious password resets, or authentication anomalies.",
      category: "account",
      inApp: true,
      email: true,
      whatsapp: true,
      slack: true,
    },
    // Billing
    {
      id: "notif_pay_fail",
      title: "Payment Failed",
      description: "When an automated recurring payment for the organization workspace fails.",
      category: "billing",
      inApp: true,
      email: true,
      whatsapp: true,
      slack: true,
    },
    {
      id: "notif_renew_rem",
      title: "Subscription Renewal Reminder",
      description: "Advance notice 7 days before annual or monthly plan renewal.",
      category: "billing",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: false,
    },
    {
      id: "notif_usage_limit",
      title: "Usage Near Allocation Limit",
      description: "When monthly WhatsApp messages, AI tokens, or storage reach 85% of tier allowance.",
      category: "billing",
      inApp: true,
      email: true,
      whatsapp: false,
      slack: true,
    },
  ],
  security: {
    authentication: {
      require2FAForAdmins: true,
      require2FAForAllMembers: false,
      sensitiveActionReauth: true,
    },
    sessionPolicy: {
      idleSessionTimeoutMinutes: 60,
      maximumSessionDurationHours: 24,
      revokeSessionsAfterPasswordChange: true,
    },
    accessPolicy: {
      allowedEmailDomains: ["@namogange.org", "@encodency.com"],
      blockPersonalEmailDomains: true,
      requireVerifiedEmail: true,
    },
    sensitiveActionProtection: {
      requireReauthRemoveMember: true,
      requireReauthDisconnectIntegration: true,
      requireReauthChangeBilling: true,
      requireReauthExportData: true,
      requireReauthTransferOwnership: true,
    },
  },
  securitySummary: {
    twoFactorAdoptionRate: 88,
    adminsWithout2FA: 1,
    activeSessionsCount: 14,
    lastSecurityPolicyChange: "Yesterday at 04:15 PM",
    lastChangedBy: "Manish Sirohi",
    securityScore: 88,
  },
  preferences: {
    locale: {
      timezone: "Asia/Kolkata (IST +5:30)",
      language: "English (United States)",
      currency: "INR (₹) - Indian Rupee",
      dateFormat: "DD/MM/YYYY",
      timeFormat: "12-hour",
      numberFormat: "Indian (1,00,000)",
      weekStartsOn: "Monday",
    },
    tables: {
      defaultRowsPerPage: 25,
      compactDensity: true,
      stickyHeaders: true,
    },
    exports: {
      csvSeparator: ",",
      exportDateFormat: "ISO 8601",
      includeOrganizationMetadata: true,
    },
  },
  dataPrivacy: {
    retention: {
      activityHistoryRetentionDays: 365,
      analyticsRetentionYears: 2,
      exportRetentionDays: 14,
    },
    privacy: {
      consentCookieBannerEnabled: true,
      explicitOptInForTracking: false,
      anonymizeClientIpAddresses: true,
      shareCrashReports: true,
    },
    recentExports: [
      {
        id: "exp_9011_all",
        requestedAt: "Sep 14, 2026, 11:20 AM",
        completedAt: "Sep 14, 2026, 11:23 AM",
        categories: ["Members", "Clients", "Campaigns", "Analytics", "Settings"],
        status: "ready",
        downloadUrl: "#",
        fileSizeBytes: 14280000, // ~14.28 MB
      },
      {
        id: "exp_8820_logs",
        requestedAt: "Aug 28, 2026, 03:45 PM",
        completedAt: "Aug 28, 2026, 03:47 PM",
        categories: ["Activity", "Settings"],
        status: "ready",
        downloadUrl: "#",
        fileSizeBytes: 3240000,
      },
    ],
  },
  activity: [
    {
      id: "act_101",
      user: {
        name: "Manish Sirohi",
        email: "manishsirohi@encodency.com",
        role: "Organization Owner",
      },
      action: "Updated organization profile",
      section: "organization",
      settingName: "Display Name & Contact Phone",
      previousValue: "Namo Public Trust | +91 98765 00000",
      newValue: "Namo Gange | +91 98765 43210",
      timestamp: "12 mins ago",
      ipAddress: "103.21.144.92 (New Delhi, IN)",
      reason: "Quarterly branding audit alignment",
    },
    {
      id: "act_102",
      user: {
        name: "Manish Sirohi",
        email: "manishsirohi@encodency.com",
        role: "Organization Owner",
      },
      action: "Enforced 2FA for Administrators",
      section: "security",
      settingName: "require2FAForAdmins",
      previousValue: "Disabled (false)",
      newValue: "Enabled (true)",
      timestamp: "Yesterday at 04:15 PM",
      ipAddress: "103.21.144.92 (New Delhi, IN)",
      reason: "SOC2 Compliance readiness check",
    },
    {
      id: "act_103",
      user: {
        name: "Priya Sharma",
        email: "priya@namogange.org",
        role: "Organization Admin",
      },
      action: "Configured primary workspace defaults",
      section: "workspace",
      settingName: "defaultLandingPage",
      previousValue: "Last Used Client",
      newValue: "Dashboard",
      timestamp: "Sep 17, 2026, 02:30 PM",
      ipAddress: "182.74.52.18 (Noida, IN)",
      reason: "Standardizing team onboarding flow",
    },
    {
      id: "act_104",
      user: {
        name: "Manish Sirohi",
        email: "manishsirohi@encodency.com",
        role: "Organization Owner",
      },
      action: "Updated notification channel matrix",
      section: "notifications",
      settingName: "Automation Failure → Slack",
      previousValue: "Disabled",
      newValue: "Enabled",
      timestamp: "Sep 15, 2026, 10:14 AM",
      ipAddress: "103.21.144.92 (New Delhi, IN)",
      reason: "Connected #ops-alerts Slack channel",
    },
    {
      id: "act_105",
      user: {
        name: "Amit Singh",
        email: "amit@namogange.org",
        role: "Organization Admin",
      },
      action: "Updated brand accent color palette",
      section: "branding",
      settingName: "primaryColor",
      previousValue: "#059669",
      newValue: "#10B981",
      timestamp: "Sep 12, 2026, 05:40 PM",
      ipAddress: "49.36.128.45 (Delhi, IN)",
      reason: "Refreshed brand design system guidelines",
    },
    {
      id: "act_106",
      user: {
        name: "Manish Sirohi",
        email: "manishsirohi@encodency.com",
        role: "Organization Owner",
      },
      action: "Added authorized email domain",
      section: "security",
      settingName: "allowedEmailDomains",
      previousValue: "['@namogange.org']",
      newValue: "['@namogange.org', '@encodency.com']",
      timestamp: "Sep 10, 2026, 11:00 AM",
      ipAddress: "103.21.144.92 (New Delhi, IN)",
      reason: "Authorized technical partner domain access",
    },
  ],
};

export const DEFAULT_CAPABILITIES: SettingsCapabilities = {
  canViewSettings: true,
  canEditOrganization: true,
  canEditBranding: true,
  canManageNotifications: true,
  canManageSecurity: true,
  canManagePreferences: true,
  canManagePrivacy: true,
  canViewAudit: true,
  canTransferOwnership: true,
  canDeactivateOrganization: true,
  canDeleteOrganization: true,
  role: "Organization Owner",
};

export const ADMIN_LIMITED_CAPABILITIES: SettingsCapabilities = {
  canViewSettings: true,
  canEditOrganization: true,
  canEditBranding: true,
  canManageNotifications: true,
  canManageSecurity: true,
  canManagePreferences: true,
  canManagePrivacy: true,
  canViewAudit: true,
  canTransferOwnership: false, // Owner only
  canDeactivateOrganization: false, // Owner only
  canDeleteOrganization: false, // Owner only
  role: "Organization Admin",
};
