import type {
  ActivityEntry,
  Ad,
  AdSet,
  Audience,
  Campaign,
  ConnectedAsset,
  Creative,
  InstantForm,
  Issue,
  Lead,
  Metrics,
  Placement,
  Platform,
} from "./types";

/**
 * Demo dataset for the Meta Ads Manager workspace. Every page reads from this
 * single graph so parent/child links and filtered views stay consistent.
 */

/* ------------------------------------------------------------------ */
/* Campaigns                                                           */
/* ------------------------------------------------------------------ */

export const campaigns: Campaign[] = [
  {
    id: "cmp-1001",
    name: "Clean Ganga Awareness - Delhi NCR",
    status: "active",
    objective: "Awareness",
    buyingType: "Auction",
    budgetType: "Daily",
    budget: 1000000,
    bidStrategy: "Highest volume",
    specialCategory: "None",
    optimization: "Reach",
    platforms: ["facebook", "instagram"],
    start: "2026-08-18",
    end: null,
    owner: "Amit Sharma",
    created: "2026-08-16T09:20:00+05:30",
    lastEdited: "2026-09-14T08:10:00+05:30",
    lastEditedBy: "Amit Sharma",
    spendCap: 5000000,
    metrics: { spend: 2854000, impressions: 125432, reach: 98210, clicks: 3842, leads: 286 },
  },
  {
    id: "cmp-1002",
    name: "Volunteer Drive Retargeting",
    status: "learning",
    objective: "Conversions",
    buyingType: "Auction",
    budgetType: "Daily",
    budget: 500000,
    bidStrategy: "Cost per result goal",
    specialCategory: "None",
    optimization: "Conversions",
    platforms: ["instagram"],
    start: "2026-08-28",
    end: null,
    owner: "Priya Verma",
    created: "2026-08-27T12:05:00+05:30",
    lastEdited: "2026-09-14T05:40:00+05:30",
    lastEditedBy: "Priya Verma",
    spendCap: 3000000,
    metrics: { spend: 1892000, impressions: 96104, reach: 72381, clicks: 2411, leads: 342 },
  },
  {
    id: "cmp-1003",
    name: "Moksha Sewa Lead Campaign",
    status: "in_review",
    objective: "Lead Generation",
    buyingType: "Auction",
    budgetType: "Daily",
    budget: 800000,
    bidStrategy: "Highest volume",
    specialCategory: "None",
    optimization: "Leads",
    platforms: ["facebook", "instagram"],
    start: "2026-09-15",
    end: "2026-10-15",
    owner: "Amit Sharma",
    created: "2026-09-13T16:45:00+05:30",
    lastEdited: "2026-09-13T18:02:00+05:30",
    lastEditedBy: "Amit Sharma",
    spendCap: 2400000,
    metrics: { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 },
  },
  {
    id: "cmp-1004",
    name: "World Rivers Day 2026",
    status: "active",
    objective: "Engagement",
    buyingType: "Auction",
    budgetType: "Lifetime",
    budget: 6000000,
    bidStrategy: "Highest volume",
    specialCategory: "None",
    optimization: "Post engagement",
    platforms: ["facebook", "instagram"],
    start: "2026-09-01",
    end: "2026-09-28",
    owner: "Neha Singh",
    created: "2026-08-30T10:15:00+05:30",
    lastEdited: "2026-09-13T14:25:00+05:30",
    lastEditedBy: "Neha Singh",
    spendCap: 6000000,
    metrics: { spend: 2143000, impressions: 112563, reach: 89214, clicks: 3120, leads: 198 },
  },
  {
    id: "cmp-1005",
    name: "Donate for a Cleaner Ganga",
    status: "completed",
    objective: "Conversions",
    buyingType: "Auction",
    budgetType: "Lifetime",
    budget: 3500000,
    bidStrategy: "Cost per result goal",
    specialCategory: "None",
    optimization: "Donations",
    platforms: ["facebook"],
    start: "2026-07-05",
    end: "2026-08-31",
    owner: "Rohit Kumar",
    created: "2026-07-02T11:00:00+05:30",
    lastEdited: "2026-09-11T09:30:00+05:30",
    lastEditedBy: "Rohit Kumar",
    spendCap: 3500000,
    metrics: { spend: 3211400, impressions: 210432, reach: 168320, clicks: 4982, leads: 412 },
  },
  {
    id: "cmp-1006",
    name: "Ghat Cleanup Volunteers - Varanasi",
    status: "paused",
    objective: "Lead Generation",
    buyingType: "Auction",
    budgetType: "Daily",
    budget: 400000,
    bidStrategy: "Highest volume",
    specialCategory: "None",
    optimization: "Leads",
    platforms: ["facebook", "instagram"],
    start: "2026-08-05",
    end: null,
    owner: "Neha Singh",
    created: "2026-08-04T15:10:00+05:30",
    lastEdited: "2026-09-09T17:45:00+05:30",
    lastEditedBy: "Neha Singh",
    spendCap: 2000000,
    metrics: { spend: 914500, impressions: 48219, reach: 39104, clicks: 1284, leads: 104 },
  },
];

/* ------------------------------------------------------------------ */
/* Ad sets                                                             */
/* ------------------------------------------------------------------ */

const pl = (rows: [string, Platform, boolean, number, number][]): Placement[] =>
  rows.map(([placement, platform, enabled, spend, leads]) => ({
    placement,
    platform,
    enabled,
    spend,
    leads,
  }));

export const adSets: AdSet[] = [
  {
    id: "as-2001",
    campaignId: "cmp-1001",
    name: "Delhi NCR - Broad 25-45",
    status: "active",
    conversionLocation: "Website",
    performanceGoal: "Maximise reach",
    attribution: "7-day click, 1-day view",
    budgetSource: "Campaign budget",
    budgetType: "Daily",
    budget: 600000,
    schedule: "18 Aug 2026 — Ongoing",
    audienceName: "NCR Environment Interest",
    audienceSize: [820000, 1250000],
    locations: ["Delhi", "Noida", "Gurugram", "Ghaziabad"],
    ageRange: "25 - 45",
    gender: "All",
    languages: ["Hindi", "English"],
    interests: ["Environmentalism", "River conservation", "Volunteering", "NGO"],
    customAudiences: [],
    lookalikes: [],
    exclusions: ["Existing donors (180d)"],
    audienceExpansion: true,
    placements: pl([
      ["Facebook Feed", "facebook", true, 1180000, 138],
      ["Instagram Feed", "instagram", true, 842000, 86],
      ["Instagram Reels", "instagram", true, 512000, 44],
      ["Facebook Stories", "facebook", true, 220000, 12],
      ["Audience Network", "audience_network", false, 0, 0],
    ]),
    metrics: { spend: 1754000, impressions: 78214, reach: 61240, clicks: 2340, leads: 180 },
    lastEdited: "2026-09-14T08:10:00+05:30",
  },
  {
    id: "as-2002",
    campaignId: "cmp-1001",
    name: "Delhi NCR - Lookalike 1%",
    status: "active",
    conversionLocation: "Website",
    performanceGoal: "Maximise reach",
    attribution: "7-day click, 1-day view",
    budgetSource: "Campaign budget",
    budgetType: "Daily",
    budget: 400000,
    schedule: "18 Aug 2026 — Ongoing",
    audienceName: "LAL 1% - Past Donors",
    audienceSize: [410000, 620000],
    locations: ["Delhi NCR"],
    ageRange: "25 - 55",
    gender: "All",
    languages: ["Hindi", "English"],
    interests: [],
    customAudiences: ["Website visitors 30d"],
    lookalikes: ["LAL 1% India - Past Donors"],
    exclusions: ["Existing donors (180d)"],
    audienceExpansion: false,
    placements: pl([
      ["Facebook Feed", "facebook", true, 610000, 62],
      ["Instagram Feed", "instagram", true, 398000, 34],
      ["Instagram Stories", "instagram", true, 92000, 10],
    ]),
    metrics: { spend: 1100000, impressions: 47218, reach: 36970, clicks: 1502, leads: 106 },
    lastEdited: "2026-09-12T11:20:00+05:30",
  },
  {
    id: "as-2003",
    campaignId: "cmp-1002",
    name: "IG Engagers 90d",
    status: "learning",
    conversionLocation: "Instant form",
    performanceGoal: "Maximise leads",
    attribution: "7-day click",
    budgetSource: "Ad set budget",
    budgetType: "Daily",
    budget: 300000,
    schedule: "28 Aug 2026 — Ongoing",
    audienceName: "Instagram Engagers 90d",
    audienceSize: [180000, 260000],
    locations: ["India"],
    ageRange: "18 - 44",
    gender: "All",
    languages: ["Hindi", "English"],
    interests: [],
    customAudiences: ["Instagram engagement 90d"],
    lookalikes: [],
    exclusions: ["Converted volunteers"],
    audienceExpansion: false,
    placements: pl([
      ["Instagram Feed", "instagram", true, 640000, 112],
      ["Instagram Reels", "instagram", true, 468000, 96],
      ["Instagram Stories", "instagram", true, 142000, 24],
    ]),
    metrics: { spend: 1250000, impressions: 61204, reach: 45318, clicks: 1580, leads: 232 },
    lastEdited: "2026-09-14T05:40:00+05:30",
  },
  {
    id: "as-2004",
    campaignId: "cmp-1002",
    name: "Website Visitors 30d",
    status: "active",
    conversionLocation: "Instant form",
    performanceGoal: "Maximise leads",
    attribution: "7-day click",
    budgetSource: "Ad set budget",
    budgetType: "Daily",
    budget: 200000,
    schedule: "28 Aug 2026 — Ongoing",
    audienceName: "Website Visitors 30d",
    audienceSize: [64000, 92000],
    locations: ["India"],
    ageRange: "22 - 50",
    gender: "All",
    languages: ["English"],
    interests: [],
    customAudiences: ["Website visitors 30d"],
    lookalikes: [],
    exclusions: [],
    audienceExpansion: false,
    placements: pl([
      ["Instagram Feed", "instagram", true, 402000, 74],
      ["Instagram Reels", "instagram", true, 240000, 36],
    ]),
    metrics: { spend: 642000, impressions: 34900, reach: 27063, clicks: 831, leads: 110 },
    lastEdited: "2026-09-10T13:05:00+05:30",
  },
  {
    id: "as-2005",
    campaignId: "cmp-1003",
    name: "Sewa Seekers - Pan India",
    status: "in_review",
    conversionLocation: "Instant form",
    performanceGoal: "Maximise leads",
    attribution: "7-day click, 1-day view",
    budgetSource: "Campaign budget",
    budgetType: "Daily",
    budget: 800000,
    schedule: "15 Sep 2026 — 15 Oct 2026",
    audienceName: "Spiritual Sewa Interest",
    audienceSize: [2100000, 3400000],
    locations: ["India"],
    ageRange: "30 - 65+",
    gender: "All",
    languages: ["Hindi"],
    interests: ["Spirituality", "Charity and causes", "Pilgrimage"],
    customAudiences: [],
    lookalikes: [],
    exclusions: [],
    audienceExpansion: true,
    placements: pl([
      ["Facebook Feed", "facebook", true, 0, 0],
      ["Instagram Feed", "instagram", true, 0, 0],
      ["Facebook Reels", "facebook", true, 0, 0],
    ]),
    metrics: { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 },
    lastEdited: "2026-09-13T18:02:00+05:30",
  },
  {
    id: "as-2006",
    campaignId: "cmp-1004",
    name: "Rivers Day - Broad Awareness",
    status: "active",
    conversionLocation: "On your post",
    performanceGoal: "Maximise engagement",
    attribution: "1-day click",
    budgetSource: "Campaign budget",
    budgetType: "Lifetime",
    budget: 3600000,
    schedule: "01 Sep 2026 — 28 Sep 2026",
    audienceName: "Rivers Day Broad",
    audienceSize: [4200000, 6100000],
    locations: ["India"],
    ageRange: "18 - 65+",
    gender: "All",
    languages: ["Hindi", "English"],
    interests: ["Nature", "Environment", "Sustainability"],
    customAudiences: [],
    lookalikes: [],
    exclusions: [],
    audienceExpansion: true,
    placements: pl([
      ["Facebook Feed", "facebook", true, 780000, 68],
      ["Instagram Reels", "instagram", true, 520000, 52],
      ["Facebook Reels", "facebook", true, 310000, 22],
    ]),
    metrics: { spend: 1610000, impressions: 84422, reach: 66910, clicks: 2340, leads: 142 },
    lastEdited: "2026-09-13T14:25:00+05:30",
  },
  {
    id: "as-2007",
    campaignId: "cmp-1004",
    name: "Rivers Day - Youth Reels",
    status: "active",
    conversionLocation: "On your post",
    performanceGoal: "Maximise engagement",
    attribution: "1-day click",
    budgetSource: "Campaign budget",
    budgetType: "Lifetime",
    budget: 2400000,
    schedule: "01 Sep 2026 — 28 Sep 2026",
    audienceName: "Youth 18-28 Reels",
    audienceSize: [1900000, 2600000],
    locations: ["India"],
    ageRange: "18 - 28",
    gender: "All",
    languages: ["Hindi", "English"],
    interests: ["Reels", "Climate action", "Student groups"],
    customAudiences: [],
    lookalikes: [],
    exclusions: [],
    audienceExpansion: true,
    placements: pl([
      ["Instagram Reels", "instagram", true, 401000, 42],
      ["Instagram Stories", "instagram", true, 132000, 14],
    ]),
    metrics: { spend: 533000, impressions: 28141, reach: 22304, clicks: 780, leads: 56 },
    lastEdited: "2026-09-08T10:05:00+05:30",
  },
  {
    id: "as-2008",
    campaignId: "cmp-1005",
    name: "Donors - High Intent",
    status: "completed",
    conversionLocation: "Website",
    performanceGoal: "Maximise donations",
    attribution: "7-day click, 1-day view",
    budgetSource: "Campaign budget",
    budgetType: "Lifetime",
    budget: 3500000,
    schedule: "05 Jul 2026 — 31 Aug 2026",
    audienceName: "Donor Lookalike 2%",
    audienceSize: [980000, 1400000],
    locations: ["India"],
    ageRange: "28 - 65+",
    gender: "All",
    languages: ["Hindi", "English"],
    interests: [],
    customAudiences: ["Past donors"],
    lookalikes: ["LAL 2% India - Donors"],
    exclusions: ["Donated last 30d"],
    audienceExpansion: false,
    placements: pl([
      ["Facebook Feed", "facebook", true, 2410000, 318],
      ["Facebook Stories", "facebook", true, 801400, 94],
    ]),
    metrics: { spend: 3211400, impressions: 210432, reach: 168320, clicks: 4982, leads: 412 },
    lastEdited: "2026-09-11T09:30:00+05:30",
  },
  {
    id: "as-2009",
    campaignId: "cmp-1006",
    name: "Varanasi - Local Volunteers",
    status: "paused",
    conversionLocation: "Instant form",
    performanceGoal: "Maximise leads",
    attribution: "7-day click",
    budgetSource: "Campaign budget",
    budgetType: "Daily",
    budget: 400000,
    schedule: "05 Aug 2026 — Paused",
    audienceName: "Varanasi 30km Radius",
    audienceSize: [78000, 110000],
    locations: ["Varanasi +30km"],
    ageRange: "18 - 40",
    gender: "All",
    languages: ["Hindi"],
    interests: ["Volunteering", "Community service"],
    customAudiences: [],
    lookalikes: [],
    exclusions: [],
    audienceExpansion: false,
    placements: pl([
      ["Facebook Feed", "facebook", true, 561000, 64],
      ["Instagram Feed", "instagram", true, 353500, 40],
    ]),
    metrics: { spend: 914500, impressions: 48219, reach: 39104, clicks: 1284, leads: 104 },
    lastEdited: "2026-09-09T17:45:00+05:30",
  },
];

/* ------------------------------------------------------------------ */
/* Ads                                                                 */
/* ------------------------------------------------------------------ */

export const ads: Ad[] = [
  {
    id: "ad-3001",
    adSetId: "as-2001",
    campaignId: "cmp-1001",
    name: "Clean Ganga - Hero Image",
    status: "active",
    format: "Single Image",
    creativeId: "cr-01",
    formId: null,
    destination: "Website — namogange.org/clean-ganga",
    primaryText:
      "Every drop counts. Join 12,000+ volunteers restoring the Ganga, one ghat at a time.",
    headline: "Be part of the Clean Ganga mission",
    description: "Volunteer, donate or simply spread the word.",
    cta: "Learn More",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["PageView", "Lead", "CompleteRegistration"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=clean_ganga",
    qualityRanking: "Above average",
    engagementRanking: "Above average",
    conversionRanking: "Average",
    reviewNote: null,
    metrics: { spend: 1180000, impressions: 52140, reach: 41020, clicks: 1620, leads: 138 },
    lastEdited: "2026-09-14T08:10:00+05:30",
  },
  {
    id: "ad-3002",
    adSetId: "as-2001",
    campaignId: "cmp-1001",
    name: "Clean Ganga - Reel 9:16",
    status: "active",
    format: "Video",
    creativeId: "cr-02",
    formId: null,
    destination: "Website — namogange.org/clean-ganga",
    primaryText: "60 seconds that will change how you see the river.",
    headline: "Watch the Ganga transform",
    description: "A short film from Haridwar.",
    cta: "Watch More",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["PageView", "ViewContent"],
    utm: "utm_source=instagram&utm_medium=paid&utm_campaign=clean_ganga",
    qualityRanking: "Above average",
    engagementRanking: "Above average",
    conversionRanking: "Above average",
    reviewNote: null,
    metrics: { spend: 574000, impressions: 26074, reach: 20220, clicks: 720, leads: 42 },
    lastEdited: "2026-09-12T09:40:00+05:30",
  },
  {
    id: "ad-3003",
    adSetId: "as-2002",
    campaignId: "cmp-1001",
    name: "Clean Ganga - Carousel Stories",
    status: "active",
    format: "Carousel",
    creativeId: "cr-03",
    formId: null,
    destination: "Website — namogange.org/stories",
    primaryText: "Five ghats. Five stories. One river.",
    headline: "Stories from the riverbank",
    description: "Swipe to meet the volunteers.",
    cta: "Learn More",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["PageView"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=stories",
    qualityRanking: "Average",
    engagementRanking: "Average",
    conversionRanking: "Average",
    reviewNote: null,
    metrics: { spend: 1100000, impressions: 47218, reach: 36970, clicks: 1502, leads: 106 },
    lastEdited: "2026-09-12T11:20:00+05:30",
  },
  {
    id: "ad-3004",
    adSetId: "as-2003",
    campaignId: "cmp-1002",
    name: "Volunteer Drive - Reel A",
    status: "active",
    format: "Video",
    creativeId: "cr-04",
    formId: "frm-4001",
    destination: "Instant form — Volunteer Sign-up 2026",
    primaryText: "Two hours a week. One cleaner river. Sign up in 30 seconds.",
    headline: "Become a Ganga volunteer",
    description: "No experience needed.",
    cta: "Sign Up",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Lead"],
    utm: "utm_source=instagram&utm_medium=paid&utm_campaign=volunteer_drive",
    qualityRanking: "Above average",
    engagementRanking: "Above average",
    conversionRanking: "Above average",
    reviewNote: null,
    metrics: { spend: 780000, impressions: 38210, reach: 28104, clicks: 980, leads: 148 },
    lastEdited: "2026-09-14T05:40:00+05:30",
  },
  {
    id: "ad-3005",
    adSetId: "as-2003",
    campaignId: "cmp-1002",
    name: "Volunteer Drive - Reel B",
    status: "active",
    format: "Video",
    creativeId: "cr-05",
    formId: "frm-4001",
    destination: "Instant form — Volunteer Sign-up 2026",
    primaryText: "Meet Kavya. She gave up two Sundays and changed a whole ghat.",
    headline: "Your Sunday can do this",
    description: "Join the next cleanup drive.",
    cta: "Sign Up",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Lead"],
    utm: "utm_source=instagram&utm_medium=paid&utm_campaign=volunteer_drive",
    qualityRanking: "Average",
    engagementRanking: "Above average",
    conversionRanking: "Average",
    reviewNote: null,
    metrics: { spend: 470000, impressions: 22994, reach: 17214, clicks: 600, leads: 84 },
    lastEdited: "2026-09-11T15:15:00+05:30",
  },
  {
    id: "ad-3006",
    adSetId: "as-2004",
    campaignId: "cmp-1002",
    name: "Retarget - Static Offer",
    status: "active",
    format: "Single Image",
    creativeId: "cr-06",
    formId: "frm-4002",
    destination: "Instant form — Quick Volunteer Interest",
    primaryText: "You visited us last week. Ready to take the next step?",
    headline: "Finish your sign-up",
    description: "It takes under a minute.",
    cta: "Sign Up",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Lead", "CompleteRegistration"],
    utm: "utm_source=instagram&utm_medium=paid&utm_campaign=retarget",
    qualityRanking: "Average",
    engagementRanking: "Average",
    conversionRanking: "Above average",
    reviewNote: null,
    metrics: { spend: 642000, impressions: 34900, reach: 27063, clicks: 831, leads: 110 },
    lastEdited: "2026-09-10T13:05:00+05:30",
  },
  {
    id: "ad-3007",
    adSetId: "as-2005",
    campaignId: "cmp-1003",
    name: "Moksha Sewa - Lead Form Ad",
    status: "in_review",
    format: "Single Image",
    creativeId: "cr-07",
    formId: "frm-4003",
    destination: "Instant form — Moksha Sewa Enquiry",
    primaryText:
      "Sewa at the ghats of Kashi. Register your interest for the October seva batch.",
    headline: "Register for Moksha Sewa",
    description: "Limited seats per batch.",
    cta: "Sign Up",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Lead"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=moksha_sewa",
    qualityRanking: "Average",
    engagementRanking: "Average",
    conversionRanking: "Average",
    reviewNote:
      "In review since 13 Sep. Most ads are reviewed within 24 hours.",
    metrics: { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 },
    lastEdited: "2026-09-13T18:02:00+05:30",
  },
  {
    id: "ad-3008",
    adSetId: "as-2005",
    campaignId: "cmp-1003",
    name: "Moksha Sewa - Reel Teaser",
    status: "rejected",
    format: "Video",
    creativeId: "cr-08",
    formId: "frm-4003",
    destination: "Instant form — Moksha Sewa Enquiry",
    primaryText: "The ghats are calling.",
    headline: "Moksha Sewa October batch",
    description: "Register now.",
    cta: "Sign Up",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Lead"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=moksha_sewa",
    qualityRanking: "Average",
    engagementRanking: "Average",
    conversionRanking: "Average",
    reviewNote:
      "Rejected under Personal Attributes: the primary text implies a personal circumstance. Edit the copy and resubmit.",
    metrics: { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 },
    lastEdited: "2026-09-13T18:40:00+05:30",
  },
  {
    id: "ad-3009",
    adSetId: "as-2006",
    campaignId: "cmp-1004",
    name: "Rivers Day - Anthem Video",
    status: "active",
    format: "Video",
    creativeId: "cr-09",
    formId: null,
    destination: "Website — namogange.org/rivers-day",
    primaryText: "One river. A billion reasons. Happy World Rivers Day.",
    headline: "World Rivers Day 2026",
    description: "Join the movement.",
    cta: "Learn More",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["PageView", "ViewContent"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=rivers_day",
    qualityRanking: "Above average",
    engagementRanking: "Above average",
    conversionRanking: "Average",
    reviewNote: null,
    metrics: { spend: 1090000, impressions: 56302, reach: 44210, clicks: 1580, leads: 96 },
    lastEdited: "2026-09-13T14:25:00+05:30",
  },
  {
    id: "ad-3010",
    adSetId: "as-2006",
    campaignId: "cmp-1004",
    name: "Rivers Day - Pledge Card",
    status: "active",
    format: "Single Image",
    creativeId: "cr-10",
    formId: "frm-4004",
    destination: "Instant form — Rivers Day Pledge",
    primaryText: "Take the pledge. Protect the river.",
    headline: "Take the Rivers Day pledge",
    description: "Add your name.",
    cta: "Sign Up",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Lead"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=rivers_day_pledge",
    qualityRanking: "Average",
    engagementRanking: "Average",
    conversionRanking: "Average",
    reviewNote: null,
    metrics: { spend: 520000, impressions: 28120, reach: 22700, clicks: 760, leads: 46 },
    lastEdited: "2026-09-07T12:10:00+05:30",
  },
  {
    id: "ad-3011",
    adSetId: "as-2007",
    campaignId: "cmp-1004",
    name: "Rivers Day - Youth Reel",
    status: "paused",
    format: "Video",
    creativeId: "cr-11",
    formId: null,
    destination: "Website — namogange.org/rivers-day",
    primaryText:
      "Your generation gets to decide what the river looks like in 2050.",
    headline: "This is your river",
    description: "Join the movement.",
    cta: "Learn More",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["PageView"],
    utm: "utm_source=instagram&utm_medium=paid&utm_campaign=rivers_day_youth",
    qualityRanking: "Below average",
    engagementRanking: "Average",
    conversionRanking: "Below average",
    reviewNote: null,
    metrics: { spend: 533000, impressions: 28141, reach: 22304, clicks: 780, leads: 56 },
    lastEdited: "2026-09-08T10:05:00+05:30",
  },
  {
    id: "ad-3012",
    adSetId: "as-2008",
    campaignId: "cmp-1005",
    name: "Donate - Matching Gift",
    status: "completed",
    format: "Single Image",
    creativeId: "cr-12",
    formId: null,
    destination: "Website — namogange.org/donate",
    primaryText:
      "Every ₹500 you give is matched. Double your impact until 31 August.",
    headline: "Your donation, doubled",
    description: "Matched by our partners.",
    cta: "Donate Now",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Purchase", "Donate"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=donate_match",
    qualityRanking: "Above average",
    engagementRanking: "Average",
    conversionRanking: "Above average",
    reviewNote: null,
    metrics: { spend: 3211400, impressions: 210432, reach: 168320, clicks: 4982, leads: 412 },
    lastEdited: "2026-09-11T09:30:00+05:30",
  },
  {
    id: "ad-3013",
    adSetId: "as-2009",
    campaignId: "cmp-1006",
    name: "Varanasi Volunteers - Form Ad",
    status: "paused",
    format: "Single Image",
    creativeId: "cr-13",
    formId: "frm-4005",
    destination: "Instant form — Varanasi Volunteer Interest",
    primaryText:
      "Clean-up drives every Saturday at Assi Ghat. Come once, stay for good.",
    headline: "Volunteer in Varanasi",
    description: "Saturdays, 6 AM.",
    cta: "Sign Up",
    page: "Namo Gange",
    instagramAccount: "@namogangetrust",
    pixel: "Namo Gange Pixel",
    pixelEvents: ["Lead"],
    utm: "utm_source=facebook&utm_medium=paid&utm_campaign=varanasi",
    qualityRanking: "Average",
    engagementRanking: "Average",
    conversionRanking: "Average",
    reviewNote: null,
    metrics: { spend: 914500, impressions: 48219, reach: 39104, clicks: 1284, leads: 104 },
    lastEdited: "2026-09-09T17:45:00+05:30",
  },
];

/* ------------------------------------------------------------------ */
/* Instant forms                                                       */
/* ------------------------------------------------------------------ */

export const instantForms: InstantForm[] = [
  {
    id: "frm-4001",
    name: "Volunteer Sign-up 2026",
    status: "active",
    type: "More volume",
    language: "Hindi + English",
    introHeadline: "Join the Namo Gange volunteer force",
    introBody:
      "Tell us a little about yourself and our coordinator will call you within 24 hours.",
    questions: [
      { id: "q1", label: "Full name", type: "Prefilled — Name", required: true, views: 4820, completions: 4610 },
      { id: "q2", label: "Phone number", type: "Prefilled — Phone", required: true, views: 4610, completions: 4180 },
      { id: "q3", label: "City", type: "Prefilled — City", required: true, views: 4180, completions: 3980 },
      { id: "q4", label: "How many hours can you volunteer per week?", type: "Multiple choice", required: true, views: 3980, completions: 3120 },
      { id: "q5", label: "Preferred drive location", type: "Multiple choice", required: false, views: 3120, completions: 2986 },
    ],
    qualification: ["At least 2 hours per week", "City must be a serviced location"],
    privacyUrl: "https://namogange.org/privacy",
    thankYouHeadline: "Thank you for signing up!",
    thankYouCta: "View upcoming drives",
    submissions: 2986,
    opens: 4820,
    qualified: 2104,
    lastUpdated: "2026-09-12T10:00:00+05:30",
  },
  {
    id: "frm-4002",
    name: "Quick Volunteer Interest",
    status: "active",
    type: "Higher intent",
    language: "English",
    introHeadline: "One minute to get started",
    introBody: "Leave your details and we will take it from here.",
    questions: [
      { id: "q1", label: "Full name", type: "Prefilled — Name", required: true, views: 1840, completions: 1790 },
      { id: "q2", label: "Email", type: "Prefilled — Email", required: true, views: 1790, completions: 1610 },
      { id: "q3", label: "Phone number", type: "Prefilled — Phone", required: true, views: 1610, completions: 1284 },
    ],
    qualification: ["Valid Indian phone number"],
    privacyUrl: "https://namogange.org/privacy",
    thankYouHeadline: "We will be in touch shortly",
    thankYouCta: "Visit website",
    submissions: 1284,
    opens: 1840,
    qualified: 802,
    lastUpdated: "2026-09-09T16:30:00+05:30",
  },
  {
    id: "frm-4003",
    name: "Moksha Sewa Enquiry",
    status: "draft",
    type: "Higher intent",
    language: "Hindi",
    introHeadline: "Moksha Sewa — October batch",
    introBody: "Register your interest for seva at the ghats of Kashi.",
    questions: [
      { id: "q1", label: "Full name", type: "Prefilled — Name", required: true, views: 0, completions: 0 },
      { id: "q2", label: "Phone number", type: "Prefilled — Phone", required: true, views: 0, completions: 0 },
      { id: "q3", label: "Preferred batch", type: "Multiple choice", required: true, views: 0, completions: 0 },
      { id: "q4", label: "Any medical conditions we should know about?", type: "Short answer", required: false, views: 0, completions: 0 },
    ],
    qualification: ["Age 18+"],
    privacyUrl: null,
    thankYouHeadline: "Registration received",
    thankYouCta: "Call us",
    submissions: 0,
    opens: 0,
    qualified: 0,
    lastUpdated: "2026-09-13T18:02:00+05:30",
  },
  {
    id: "frm-4004",
    name: "Rivers Day Pledge",
    status: "active",
    type: "More volume",
    language: "English",
    introHeadline: "Take the Rivers Day pledge",
    introBody:
      "Add your name to the pledge and we will send you the pledge certificate.",
    questions: [
      { id: "q1", label: "Full name", type: "Prefilled — Name", required: true, views: 920, completions: 902 },
      { id: "q2", label: "Email", type: "Prefilled — Email", required: true, views: 902, completions: 742 },
    ],
    qualification: [],
    privacyUrl: "https://namogange.org/privacy",
    thankYouHeadline: "Your pledge is recorded",
    thankYouCta: "Download certificate",
    submissions: 742,
    opens: 920,
    qualified: 410,
    lastUpdated: "2026-09-05T11:15:00+05:30",
  },
  {
    id: "frm-4005",
    name: "Varanasi Volunteer Interest",
    status: "archived",
    type: "More volume",
    language: "Hindi",
    introHeadline: "Assi Ghat Saturday drives",
    introBody: "Sign up for the weekly clean-up drive.",
    questions: [
      { id: "q1", label: "Full name", type: "Prefilled — Name", required: true, views: 640, completions: 618 },
      { id: "q2", label: "Phone number", type: "Prefilled — Phone", required: true, views: 618, completions: 512 },
      { id: "q3", label: "Which Saturday works for you?", type: "Multiple choice", required: true, views: 512, completions: 404 },
    ],
    qualification: ["Lives within 30km of Varanasi"],
    privacyUrl: "https://namogange.org/privacy",
    thankYouHeadline: "See you at the ghat!",
    thankYouCta: "Get directions",
    submissions: 404,
    opens: 640,
    qualified: 248,
    lastUpdated: "2026-08-29T09:45:00+05:30",
  },
];

/* ------------------------------------------------------------------ */
/* Leads                                                               */
/* ------------------------------------------------------------------ */

type LeadSeed = Omit<
  Lead,
  "timeline" | "notes" | "tasks" | "appointments" | "documents" | "consent"
> &
  Partial<
    Pick<
      Lead,
      "timeline" | "notes" | "tasks" | "appointments" | "documents" | "consent"
    >
  >;

function lead(seed: LeadSeed): Lead {
  const formName =
    instantForms.find((f) => f.id === seed.formId)?.name ?? "an instant form";
  return {
    consent: "Consented to be contacted by phone and WhatsApp at submission.",
    timeline: [
      {
        at: seed.submittedAt,
        actor: "Meta",
        type: "lead",
        text: `Lead submitted through ${formName}.`,
      },
    ],
    notes: [],
    tasks: [],
    appointments: [],
    documents: [],
    ...seed,
  };
}

export const leads: Lead[] = [
  lead({
    id: "LD-100023",
    name: "Rajesh Kumar",
    phone: "+91 98765 43210",
    email: "rajesh@techcorp.in",
    city: "Noida",
    company: "TechCorp India",
    campaignId: "cmp-1002",
    adSetId: "as-2003",
    adId: "ad-3004",
    formId: "frm-4001",
    stage: "Qualified",
    score: 84,
    owner: "Amit Sharma",
    submittedAt: "2026-09-14T10:45:00+05:30",
    lastActivity: "2026-09-14T12:10:00+05:30",
    responseMinutes: 18,
    answers: [
      { question: "Full name", answer: "Rajesh Kumar" },
      { question: "Phone number", answer: "+91 98765 43210" },
      { question: "City", answer: "Noida" },
      { question: "How many hours can you volunteer per week?", answer: "4-6 hours" },
      { question: "Preferred drive location", answer: "Yamuna Ghat, Noida" },
    ],
    timeline: [
      { at: "2026-09-14T10:45:00+05:30", actor: "Meta", type: "lead", text: "Lead submitted through Volunteer Sign-up 2026." },
      { at: "2026-09-14T11:03:00+05:30", actor: "Amit Sharma", type: "call", text: "Outbound call — 4 min 12 s. Interested in weekend drives." },
      { at: "2026-09-14T11:20:00+05:30", actor: "Amit Sharma", type: "stage", text: "Stage changed from New to Contacted." },
      { at: "2026-09-14T12:10:00+05:30", actor: "Amit Sharma", type: "stage", text: "Stage changed from Contacted to Qualified." },
    ],
    notes: [
      { at: "2026-09-14T11:25:00+05:30", author: "Amit Sharma", text: "Can commit to alternate Saturdays. Wants to bring 3 colleagues." },
    ],
    tasks: [{ title: "Send volunteer onboarding kit", due: "2026-09-15", done: false, owner: "Amit Sharma" }],
    appointments: [{ title: "Orientation call", at: "2026-09-16T18:00:00+05:30", with: "Amit Sharma" }],
    documents: [{ name: "call-recording-100023.mp3", size: "1.8 MB", at: "2026-09-14T11:03:00+05:30" }],
  }),
  lead({
    id: "LD-100024",
    name: "Sneha Sharma",
    phone: "+91 91234 56789",
    email: "sneha.s@designstudio.com",
    city: "Gurugram",
    company: "Design Studio",
    campaignId: "cmp-1002",
    adSetId: "as-2004",
    adId: "ad-3006",
    formId: "frm-4002",
    stage: "Contacted",
    score: 65,
    owner: "Priya Verma",
    submittedAt: "2026-09-14T11:30:00+05:30",
    lastActivity: "2026-09-14T13:05:00+05:30",
    responseMinutes: 42,
    answers: [
      { question: "Full name", answer: "Sneha Sharma" },
      { question: "Email", answer: "sneha.s@designstudio.com" },
      { question: "Phone number", answer: "+91 91234 56789" },
    ],
    timeline: [
      { at: "2026-09-14T11:30:00+05:30", actor: "Meta", type: "lead", text: "Lead submitted through Quick Volunteer Interest." },
      { at: "2026-09-14T12:12:00+05:30", actor: "Priya Verma", type: "whatsapp", text: "WhatsApp sent — volunteer intro message." },
      { at: "2026-09-14T13:05:00+05:30", actor: "Sneha Sharma", type: "reply", text: "Replied: asked for weekday options." },
    ],
    notes: [
      { at: "2026-09-14T13:08:00+05:30", author: "Priya Verma", text: "Only free on weekday evenings — check if the Gurugram chapter has evening drives." },
    ],
    tasks: [{ title: "Confirm weekday drive slot", due: "2026-09-16", done: false, owner: "Priya Verma" }],
  }),
  lead({
    id: "LD-100025",
    name: "Unknown User",
    phone: "—",
    email: "test1234@gmail.com",
    city: "Delhi",
    company: "—",
    campaignId: "cmp-1001",
    adSetId: "as-2001",
    adId: "ad-3001",
    formId: "frm-4002",
    stage: "Spam",
    score: 12,
    owner: "Unassigned",
    submittedAt: "2026-09-14T13:15:00+05:30",
    lastActivity: "2026-09-14T13:40:00+05:30",
    responseMinutes: null,
    answers: [
      { question: "Full name", answer: "asdf asdf" },
      { question: "Email", answer: "test1234@gmail.com" },
      { question: "Phone number", answer: "0000000000" },
    ],
  }),
  lead({
    id: "LD-100026",
    name: "Vikram Nair",
    phone: "+91 99887 76655",
    email: "vikram.nair@gmail.com",
    city: "Varanasi",
    company: "—",
    campaignId: "cmp-1006",
    adSetId: "as-2009",
    adId: "ad-3013",
    formId: "frm-4005",
    stage: "Converted",
    score: 92,
    owner: "Neha Singh",
    submittedAt: "2026-09-11T09:05:00+05:30",
    lastActivity: "2026-09-13T17:20:00+05:30",
    responseMinutes: 9,
    answers: [
      { question: "Full name", answer: "Vikram Nair" },
      { question: "Phone number", answer: "+91 99887 76655" },
      { question: "Which Saturday works for you?", answer: "Every Saturday" },
    ],
    timeline: [
      { at: "2026-09-11T09:05:00+05:30", actor: "Meta", type: "lead", text: "Lead submitted through Varanasi Volunteer Interest." },
      { at: "2026-09-11T09:14:00+05:30", actor: "Neha Singh", type: "call", text: "Outbound call — 6 min 40 s." },
      { at: "2026-09-12T08:00:00+05:30", actor: "Neha Singh", type: "meeting", text: "Attended Assi Ghat drive." },
      { at: "2026-09-13T17:20:00+05:30", actor: "Neha Singh", type: "stage", text: "Stage changed to Converted." },
    ],
    notes: [
      { at: "2026-09-12T12:00:00+05:30", author: "Neha Singh", text: "Excellent fit — offered him the ghat coordinator role." },
    ],
  }),
  lead({
    id: "LD-100027",
    name: "Ananya Iyer",
    phone: "+91 90000 11223",
    email: "ananya.iyer@outlook.com",
    city: "Mumbai",
    company: "Kraft Media",
    campaignId: "cmp-1004",
    adSetId: "as-2006",
    adId: "ad-3010",
    formId: "frm-4004",
    stage: "New",
    score: 58,
    owner: "Unassigned",
    submittedAt: "2026-09-14T14:02:00+05:30",
    lastActivity: "2026-09-14T14:02:00+05:30",
    responseMinutes: null,
    answers: [
      { question: "Full name", answer: "Ananya Iyer" },
      { question: "Email", answer: "ananya.iyer@outlook.com" },
    ],
  }),
  lead({
    id: "LD-100028",
    name: "Mohammed Arif",
    phone: "+91 98191 22334",
    email: "m.arif@gmail.com",
    city: "Kanpur",
    company: "—",
    campaignId: "cmp-1002",
    adSetId: "as-2003",
    adId: "ad-3005",
    formId: "frm-4001",
    stage: "Meeting Scheduled",
    score: 78,
    owner: "Amit Sharma",
    submittedAt: "2026-09-13T16:20:00+05:30",
    lastActivity: "2026-09-14T09:15:00+05:30",
    responseMinutes: 25,
    answers: [
      { question: "Full name", answer: "Mohammed Arif" },
      { question: "Phone number", answer: "+91 98191 22334" },
      { question: "City", answer: "Kanpur" },
      { question: "How many hours can you volunteer per week?", answer: "2-4 hours" },
    ],
    appointments: [{ title: "Kanpur chapter intro", at: "2026-09-17T11:00:00+05:30", with: "Amit Sharma" }],
  }),
  lead({
    id: "LD-100029",
    name: "Deepika Rao",
    phone: "+91 97777 65432",
    email: "deepika.rao@zylo.in",
    city: "Bengaluru",
    company: "Zylo Labs",
    campaignId: "cmp-1002",
    adSetId: "as-2004",
    adId: "ad-3006",
    formId: "frm-4002",
    stage: "Lost",
    score: 34,
    owner: "Priya Verma",
    submittedAt: "2026-09-10T18:40:00+05:30",
    lastActivity: "2026-09-12T10:00:00+05:30",
    responseMinutes: 120,
    answers: [
      { question: "Full name", answer: "Deepika Rao" },
      { question: "Email", answer: "deepika.rao@zylo.in" },
      { question: "Phone number", answer: "+91 97777 65432" },
    ],
    notes: [
      { at: "2026-09-12T10:00:00+05:30", author: "Priya Verma", text: "No chapter in Bengaluru yet. Added to waitlist." },
    ],
  }),
  lead({
    id: "LD-100030",
    name: "Harpreet Singh",
    phone: "+91 98111 44556",
    email: "harpreet@gmail.com",
    city: "Delhi",
    company: "—",
    campaignId: "cmp-1002",
    adSetId: "as-2003",
    adId: "ad-3004",
    formId: "frm-4001",
    stage: "Qualified",
    score: 88,
    owner: "Amit Sharma",
    submittedAt: "2026-09-13T08:10:00+05:30",
    lastActivity: "2026-09-13T09:02:00+05:30",
    responseMinutes: 14,
    answers: [
      { question: "Full name", answer: "Harpreet Singh" },
      { question: "Phone number", answer: "+91 98111 44556" },
      { question: "City", answer: "Delhi" },
      { question: "How many hours can you volunteer per week?", answer: "6+ hours" },
    ],
  }),
  lead({
    id: "LD-100031",
    name: "Kavya Menon",
    phone: "+91 93333 22110",
    email: "kavya.menon@gmail.com",
    city: "Lucknow",
    company: "—",
    campaignId: "cmp-1004",
    adSetId: "as-2006",
    adId: "ad-3010",
    formId: "frm-4004",
    stage: "Contacted",
    score: 61,
    owner: "Neha Singh",
    submittedAt: "2026-09-12T15:30:00+05:30",
    lastActivity: "2026-09-13T11:00:00+05:30",
    responseMinutes: 55,
    answers: [
      { question: "Full name", answer: "Kavya Menon" },
      { question: "Email", answer: "kavya.menon@gmail.com" },
    ],
  }),
  lead({
    id: "LD-100032",
    name: "Suresh Patel",
    phone: "+91 94444 55667",
    email: "suresh.patel@shreeco.in",
    city: "Ahmedabad",
    company: "Shree & Co",
    campaignId: "cmp-1005",
    adSetId: "as-2008",
    adId: "ad-3012",
    formId: "frm-4002",
    stage: "Converted",
    score: 95,
    owner: "Rohit Kumar",
    submittedAt: "2026-08-28T12:00:00+05:30",
    lastActivity: "2026-08-30T16:30:00+05:30",
    responseMinutes: 7,
    answers: [
      { question: "Full name", answer: "Suresh Patel" },
      { question: "Email", answer: "suresh.patel@shreeco.in" },
      { question: "Phone number", answer: "+91 94444 55667" },
    ],
    notes: [
      { at: "2026-08-30T16:30:00+05:30", author: "Rohit Kumar", text: "Corporate matching donation of ₹2,50,000 confirmed." },
    ],
  }),
  lead({
    id: "LD-100033",
    name: "Ritu Agarwal",
    phone: "+91 95555 88990",
    email: "ritu.agarwal@gmail.com",
    city: "Jaipur",
    company: "—",
    campaignId: "cmp-1002",
    adSetId: "as-2003",
    adId: "ad-3005",
    formId: "frm-4001",
    stage: "New",
    score: 72,
    owner: "Unassigned",
    submittedAt: "2026-09-14T09:20:00+05:30",
    lastActivity: "2026-09-14T09:20:00+05:30",
    responseMinutes: null,
    answers: [
      { question: "Full name", answer: "Ritu Agarwal" },
      { question: "Phone number", answer: "+91 95555 88990" },
      { question: "City", answer: "Jaipur" },
      { question: "How many hours can you volunteer per week?", answer: "2-4 hours" },
    ],
  }),
  lead({
    id: "LD-100034",
    name: "Imran Qureshi",
    phone: "+91 96666 77889",
    email: "imran.q@gmail.com",
    city: "Varanasi",
    company: "—",
    campaignId: "cmp-1006",
    adSetId: "as-2009",
    adId: "ad-3013",
    formId: "frm-4005",
    stage: "Qualified",
    score: 81,
    owner: "Neha Singh",
    submittedAt: "2026-09-09T07:45:00+05:30",
    lastActivity: "2026-09-10T10:15:00+05:30",
    responseMinutes: 30,
    answers: [
      { question: "Full name", answer: "Imran Qureshi" },
      { question: "Phone number", answer: "+91 96666 77889" },
      { question: "Which Saturday works for you?", answer: "First Saturday" },
    ],
  }),
];

/* ------------------------------------------------------------------ */
/* Audiences                                                           */
/* ------------------------------------------------------------------ */

export const audiences: Audience[] = [
  { id: "aud-01", name: "NCR Environment Interest", kind: "saved", source: "Interest targeting", size: 1035000, matchRate: null, similarity: null, country: null, sourceAudience: null, locations: "Delhi, Noida, Gurugram, Ghaziabad", ageRange: "25 - 45", gender: "All", interests: ["Environmentalism", "River conservation", "Volunteering"], usedIn: ["as-2001"], status: "Ready", lastSync: "2026-09-14T06:00:00+05:30" },
  { id: "aud-02", name: "Spiritual Sewa Interest", kind: "saved", source: "Interest targeting", size: 2750000, matchRate: null, similarity: null, country: null, sourceAudience: null, locations: "India", ageRange: "30 - 65+", gender: "All", interests: ["Spirituality", "Charity and causes", "Pilgrimage"], usedIn: ["as-2005"], status: "Ready", lastSync: "2026-09-13T06:00:00+05:30" },
  { id: "aud-03", name: "Varanasi 30km Radius", kind: "saved", source: "Location targeting", size: 94000, matchRate: null, similarity: null, country: null, sourceAudience: null, locations: "Varanasi +30km", ageRange: "18 - 40", gender: "All", interests: ["Volunteering", "Community service"], usedIn: ["as-2009"], status: "Too small", lastSync: "2026-09-09T06:00:00+05:30" },
  { id: "aud-04", name: "Past donors", kind: "custom", source: "Customer List", size: 18420, matchRate: 72, similarity: null, country: null, sourceAudience: null, locations: "—", ageRange: "—", gender: "—", interests: [], usedIn: ["as-2008"], status: "Ready", lastSync: "2026-09-14T04:30:00+05:30" },
  { id: "aud-05", name: "Website visitors 30d", kind: "custom", source: "Website Visitors", size: 78200, matchRate: null, similarity: null, country: null, sourceAudience: null, locations: "—", ageRange: "—", gender: "—", interests: [], usedIn: ["as-2002", "as-2004"], status: "Ready", lastSync: "2026-09-14T05:00:00+05:30" },
  { id: "aud-06", name: "Instagram engagement 90d", kind: "custom", source: "Instagram Engagement", size: 221400, matchRate: null, similarity: null, country: null, sourceAudience: null, locations: "—", ageRange: "—", gender: "—", interests: [], usedIn: ["as-2003"], status: "Ready", lastSync: "2026-09-14T05:00:00+05:30" },
  { id: "aud-07", name: "Lead form openers 180d", kind: "custom", source: "Lead Form Engagement", size: 42900, matchRate: null, similarity: null, country: null, sourceAudience: null, locations: "—", ageRange: "—", gender: "—", interests: [], usedIn: [], status: "Updating", lastSync: "2026-09-14T07:10:00+05:30" },
  { id: "aud-08", name: "Video viewers 75% - Rivers Day", kind: "custom", source: "Video Viewers", size: 31600, matchRate: null, similarity: null, country: null, sourceAudience: null, locations: "—", ageRange: "—", gender: "—", interests: [], usedIn: [], status: "Sync failed", lastSync: "2026-09-12T22:40:00+05:30" },
  { id: "aud-09", name: "LAL 1% India - Past Donors", kind: "lookalike", source: "Lookalike", size: 512000, matchRate: null, similarity: 1, country: "India", sourceAudience: "Past donors", locations: "India", ageRange: "—", gender: "—", interests: [], usedIn: ["as-2002"], status: "Ready", lastSync: "2026-09-14T04:45:00+05:30" },
  { id: "aud-10", name: "LAL 2% India - Donors", kind: "lookalike", source: "Lookalike", size: 1024000, matchRate: null, similarity: 2, country: "India", sourceAudience: "Past donors", locations: "India", ageRange: "—", gender: "—", interests: [], usedIn: ["as-2008"], status: "Ready", lastSync: "2026-09-14T04:45:00+05:30" },
  { id: "aud-11", name: "LAL 3% - IG Engagers", kind: "lookalike", source: "Lookalike", size: 1536000, matchRate: null, similarity: 3, country: "India", sourceAudience: "Instagram engagement 90d", locations: "India", ageRange: "—", gender: "—", interests: [], usedIn: [], status: "Updating", lastSync: "2026-09-14T07:20:00+05:30" },
];

/* ------------------------------------------------------------------ */
/* Creatives                                                           */
/* ------------------------------------------------------------------ */

const IMG_A = "/images/ads-manager/renovation-home.png";
const IMG_B = "/images/ads-manager/skincare-serum.png";

export const creatives: Creative[] = [
  { id: "cr-01", name: "Clean Ganga Hero 1:1", type: "Image", ratio: "1:1", dimensions: "1080 × 1080", fileSize: "412 KB", src: IMG_A, usedInAds: ["ad-3001"], performance: "Top performer", uploaded: "2026-08-16", metrics: { spend: 1180000, impressions: 52140, reach: 41020, clicks: 1620, leads: 138 } },
  { id: "cr-02", name: "Ganga Film Cut 9:16", type: "Video", ratio: "9:16", dimensions: "1080 × 1920", fileSize: "14.2 MB", src: IMG_B, usedInAds: ["ad-3002"], performance: "Healthy", uploaded: "2026-08-20", metrics: { spend: 574000, impressions: 26074, reach: 20220, clicks: 720, leads: 42 } },
  { id: "cr-03", name: "Ghat Stories Carousel", type: "Carousel", ratio: "4:5", dimensions: "1080 × 1350", fileSize: "1.8 MB", src: IMG_A, usedInAds: ["ad-3003"], performance: "Healthy", uploaded: "2026-08-22", metrics: { spend: 1100000, impressions: 47218, reach: 36970, clicks: 1502, leads: 106 } },
  { id: "cr-04", name: "Volunteer Reel A", type: "Video", ratio: "9:16", dimensions: "1080 × 1920", fileSize: "11.6 MB", src: IMG_B, usedInAds: ["ad-3004"], performance: "Top performer", uploaded: "2026-08-28", metrics: { spend: 780000, impressions: 38210, reach: 28104, clicks: 980, leads: 148 } },
  { id: "cr-05", name: "Volunteer Reel B - Kavya", type: "Video", ratio: "9:16", dimensions: "1080 × 1920", fileSize: "9.4 MB", src: IMG_A, usedInAds: ["ad-3005"], performance: "Healthy", uploaded: "2026-08-29", metrics: { spend: 470000, impressions: 22994, reach: 17214, clicks: 600, leads: 84 } },
  { id: "cr-06", name: "Retarget Static 4:5", type: "Image", ratio: "4:5", dimensions: "1080 × 1350", fileSize: "386 KB", src: IMG_B, usedInAds: ["ad-3006"], performance: "Healthy", uploaded: "2026-09-01", metrics: { spend: 642000, impressions: 34900, reach: 27063, clicks: 831, leads: 110 } },
  { id: "cr-07", name: "Moksha Sewa Key Visual", type: "Image", ratio: "1:1", dimensions: "1080 × 1080", fileSize: "498 KB", src: IMG_A, usedInAds: ["ad-3007"], performance: "Not used", uploaded: "2026-09-13", metrics: { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 } },
  { id: "cr-08", name: "Moksha Sewa Teaser", type: "Video", ratio: "9:16", dimensions: "1080 × 1920", fileSize: "8.9 MB", src: IMG_B, usedInAds: ["ad-3008"], performance: "Not used", uploaded: "2026-09-13", metrics: { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 } },
  { id: "cr-09", name: "Rivers Day Anthem", type: "Video", ratio: "1.91:1", dimensions: "1920 × 1005", fileSize: "22.4 MB", src: IMG_A, usedInAds: ["ad-3009"], performance: "Top performer", uploaded: "2026-08-30", metrics: { spend: 1090000, impressions: 56302, reach: 44210, clicks: 1580, leads: 96 } },
  { id: "cr-10", name: "Rivers Day Pledge Card", type: "Image", ratio: "1:1", dimensions: "1080 × 1080", fileSize: "322 KB", src: IMG_B, usedInAds: ["ad-3010"], performance: "Healthy", uploaded: "2026-09-02", metrics: { spend: 520000, impressions: 28120, reach: 22700, clicks: 760, leads: 46 } },
  { id: "cr-11", name: "Youth Reel - 2050", type: "Video", ratio: "9:16", dimensions: "1080 × 1920", fileSize: "10.1 MB", src: IMG_A, usedInAds: ["ad-3011"], performance: "Underperforming", uploaded: "2026-09-03", metrics: { spend: 533000, impressions: 28141, reach: 22304, clicks: 780, leads: 56 } },
  { id: "cr-12", name: "Matching Gift Banner", type: "Image", ratio: "1.91:1", dimensions: "1200 × 628", fileSize: "244 KB", src: IMG_B, usedInAds: ["ad-3012"], performance: "Top performer", uploaded: "2026-07-02", metrics: { spend: 3211400, impressions: 210432, reach: 168320, clicks: 4982, leads: 412 } },
  { id: "cr-13", name: "Assi Ghat Saturday", type: "Image", ratio: "4:5", dimensions: "1080 × 1350", fileSize: "402 KB", src: IMG_A, usedInAds: ["ad-3013"], performance: "Healthy", uploaded: "2026-08-04", metrics: { spend: 914500, impressions: 48219, reach: 39104, clicks: 1284, leads: 104 } },
  { id: "cr-14", name: "Ganga Aarti 4:5", type: "Image", ratio: "4:5", dimensions: "1080 × 1350", fileSize: "455 KB", src: IMG_B, usedInAds: [], performance: "Not used", uploaded: "2026-09-06", metrics: { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 } },
];

/* ------------------------------------------------------------------ */
/* Issues                                                              */
/* ------------------------------------------------------------------ */

export const issues: Issue[] = [
  {
    id: "iss-01",
    severity: "connection",
    title: "Instagram authorization expired",
    detail:
      "The access token for @namogangetrust expired on 12 Sep. Instagram placements will stop delivering within 24 hours.",
    entityLabel: "@namogangetrust",
    entityHref: "/admin/meta/ads/assets",
    campaign: null,
    detected: "2026-09-12T22:40:00+05:30",
    resolved: false,
    actionLabel: "Reconnect Instagram",
    actionHref: "/admin/meta/ads/assets#instagram",
  },
  {
    id: "iss-02",
    severity: "blocking",
    title: "Instant form is missing a privacy policy URL",
    detail:
      "Moksha Sewa Enquiry cannot be published until a privacy policy URL is added. Meta requires one on every lead form.",
    entityLabel: "Moksha Sewa Enquiry",
    entityHref: "/admin/meta/ads/forms/frm-4003",
    campaign: "Moksha Sewa Lead Campaign",
    detected: "2026-09-13T18:05:00+05:30",
    resolved: false,
    actionLabel: "Fix Form",
    actionHref: "/admin/meta/ads/forms/frm-4003",
  },
  {
    id: "iss-03",
    severity: "policy",
    title: "Ad creative rejected — Personal Attributes",
    detail:
      "Moksha Sewa - Reel Teaser was rejected because the primary text implies a personal circumstance. Edit the copy and resubmit for review.",
    entityLabel: "Moksha Sewa - Reel Teaser",
    entityHref: "/admin/meta/ads/ads/ad-3008",
    campaign: "Moksha Sewa Lead Campaign",
    detected: "2026-09-13T18:40:00+05:30",
    resolved: false,
    actionLabel: "View Reason",
    actionHref: "/admin/meta/ads/ads/ad-3008",
  },
  {
    id: "iss-04",
    severity: "warning",
    title: "Audience may be too narrow",
    detail:
      "Varanasi - Local Volunteers has an estimated audience of 78K–110K. Ad sets under 150K often exit the learning phase slowly.",
    entityLabel: "Varanasi - Local Volunteers",
    entityHref: "/admin/meta/ads/adsets/as-2009",
    campaign: "Ghat Cleanup Volunteers - Varanasi",
    detected: "2026-09-09T11:00:00+05:30",
    resolved: false,
    actionLabel: "Edit Ad Set",
    actionHref: "/admin/meta/ads/adsets/as-2009",
  },
  {
    id: "iss-05",
    severity: "warning",
    title: "Lifetime budget almost exhausted",
    detail:
      "World Rivers Day 2026 has spent ₹21,430 of its ₹60,000 lifetime budget with 14 days left at the current pace.",
    entityLabel: "World Rivers Day 2026",
    entityHref: "/admin/meta/ads/campaigns/cmp-1004",
    campaign: "World Rivers Day 2026",
    detected: "2026-09-13T09:00:00+05:30",
    resolved: false,
    actionLabel: "Edit Budget",
    actionHref: "/admin/meta/ads/campaigns/cmp-1004",
  },
  {
    id: "iss-06",
    severity: "warning",
    title: "Creative quality ranking is below average",
    detail:
      "Rivers Day - Youth Reel ranks below average on quality and conversion. Refresh the creative or pause the ad.",
    entityLabel: "Rivers Day - Youth Reel",
    entityHref: "/admin/meta/ads/ads/ad-3011",
    campaign: "World Rivers Day 2026",
    detected: "2026-09-08T10:30:00+05:30",
    resolved: false,
    actionLabel: "Review Creative",
    actionHref: "/admin/meta/ads/ads/ad-3011",
  },
  {
    id: "iss-07",
    severity: "connection",
    title: "Custom audience failed to sync",
    detail:
      "Video viewers 75% - Rivers Day last synced successfully on 12 Sep. Meta returned a temporary data source error.",
    entityLabel: "Video viewers 75% - Rivers Day",
    entityHref: "/admin/meta/ads/audiences?tab=custom",
    campaign: null,
    detected: "2026-09-12T22:40:00+05:30",
    resolved: false,
    actionLabel: "Retry Sync",
    actionHref: "/admin/meta/ads/audiences?tab=custom",
  },
  {
    id: "iss-08",
    severity: "warning",
    title: "Pixel event missing on donation page",
    detail:
      "The Purchase event has not fired from namogange.org/donate in the last 7 days.",
    entityLabel: "Namo Gange Pixel",
    entityHref: "/admin/meta/ads/assets",
    campaign: "Donate for a Cleaner Ganga",
    detected: "2026-09-07T14:20:00+05:30",
    resolved: true,
    actionLabel: "Open Data Sources",
    actionHref: "/admin/meta/ads/assets#pixel",
  },
  {
    id: "iss-09",
    severity: "blocking",
    title: "Ads Management permission missing",
    detail:
      "The connected user did not have ads_management on the Namo Gange Official ad account, so campaigns could not be paused from here.",
    entityLabel: "Namo Gange Official",
    entityHref: "/admin/meta/ads/assets",
    campaign: null,
    detected: "2026-09-06T08:00:00+05:30",
    resolved: true,
    actionLabel: "Refresh Permissions",
    actionHref: "/admin/meta/ads/assets#ad-account",
  },
];

/* ------------------------------------------------------------------ */
/* Activity log                                                        */
/* ------------------------------------------------------------------ */

export const activityLog: ActivityEntry[] = [
  { id: "act-01", at: "2026-09-14T08:10:00+05:30", user: "Amit Sharma", action: "Budget changed", entityType: "Campaign", entityLabel: "Clean Ganga Awareness - Delhi NCR", entityHref: "/admin/meta/ads/campaigns/cmp-1001", campaign: "Clean Ganga Awareness - Delhi NCR", oldValue: "₹8,000/day", newValue: "₹10,000/day", source: "Ads Manager" },
  { id: "act-02", at: "2026-09-14T05:40:00+05:30", user: "Priya Verma", action: "Targeting changed", entityType: "Ad Set", entityLabel: "IG Engagers 90d", entityHref: "/admin/meta/ads/adsets/as-2003", campaign: "Volunteer Drive Retargeting", oldValue: "Age 18-35", newValue: "Age 18-44", source: "Ads Manager" },
  { id: "act-03", at: "2026-09-13T18:40:00+05:30", user: "Meta", action: "Ad rejected", entityType: "Ad", entityLabel: "Moksha Sewa - Reel Teaser", entityHref: "/admin/meta/ads/ads/ad-3008", campaign: "Moksha Sewa Lead Campaign", oldValue: "In review", newValue: "Rejected", source: "API" },
  { id: "act-04", at: "2026-09-13T18:02:00+05:30", user: "Amit Sharma", action: "Campaign published", entityType: "Campaign", entityLabel: "Moksha Sewa Lead Campaign", entityHref: "/admin/meta/ads/campaigns/cmp-1003", campaign: "Moksha Sewa Lead Campaign", oldValue: "Draft", newValue: "In review", source: "Ads Manager" },
  { id: "act-05", at: "2026-09-13T16:45:00+05:30", user: "Amit Sharma", action: "Campaign created", entityType: "Campaign", entityLabel: "Moksha Sewa Lead Campaign", entityHref: "/admin/meta/ads/campaigns/cmp-1003", campaign: "Moksha Sewa Lead Campaign", oldValue: null, newValue: "Lead Generation", source: "Ads Manager" },
  { id: "act-06", at: "2026-09-13T14:25:00+05:30", user: "Neha Singh", action: "Ad creative changed", entityType: "Ad", entityLabel: "Rivers Day - Anthem Video", entityHref: "/admin/meta/ads/ads/ad-3009", campaign: "World Rivers Day 2026", oldValue: "Rivers Day Anthem v1", newValue: "Rivers Day Anthem", source: "Ads Manager" },
  { id: "act-07", at: "2026-09-12T22:40:00+05:30", user: "System", action: "Connection error", entityType: "Account", entityLabel: "@namogangetrust", entityHref: "/admin/meta/ads/assets", campaign: null, oldValue: "Connected", newValue: "Needs reauthorization", source: "Automation" },
  { id: "act-08", at: "2026-09-12T11:20:00+05:30", user: "Amit Sharma", action: "Placement changed", entityType: "Ad Set", entityLabel: "Delhi NCR - Lookalike 1%", entityHref: "/admin/meta/ads/adsets/as-2002", campaign: "Clean Ganga Awareness - Delhi NCR", oldValue: "Advantage+ placements", newValue: "Manual placements", source: "Ads Manager" },
  { id: "act-09", at: "2026-09-12T10:00:00+05:30", user: "Priya Verma", action: "Form changed", entityType: "Instant Form", entityLabel: "Volunteer Sign-up 2026", entityHref: "/admin/meta/ads/forms/frm-4001", campaign: "Volunteer Drive Retargeting", oldValue: "4 questions", newValue: "5 questions", source: "Ads Manager" },
  { id: "act-10", at: "2026-09-09T17:45:00+05:30", user: "Neha Singh", action: "Campaign paused", entityType: "Campaign", entityLabel: "Ghat Cleanup Volunteers - Varanasi", entityHref: "/admin/meta/ads/campaigns/cmp-1006", campaign: "Ghat Cleanup Volunteers - Varanasi", oldValue: "Active", newValue: "Paused", source: "Ads Manager" },
  { id: "act-11", at: "2026-09-08T10:05:00+05:30", user: "Neha Singh", action: "Ad paused", entityType: "Ad", entityLabel: "Rivers Day - Youth Reel", entityHref: "/admin/meta/ads/ads/ad-3011", campaign: "World Rivers Day 2026", oldValue: "Active", newValue: "Paused", source: "Ads Manager" },
  { id: "act-12", at: "2026-09-06T08:00:00+05:30", user: "Rohit Kumar", action: "Permission changed", entityType: "Account", entityLabel: "Namo Gange Official", entityHref: "/admin/meta/ads/assets", campaign: null, oldValue: "ads_read", newValue: "ads_read, ads_management", source: "Ads Manager" },
  { id: "act-13", at: "2026-09-05T11:15:00+05:30", user: "Neha Singh", action: "Form published", entityType: "Instant Form", entityLabel: "Rivers Day Pledge", entityHref: "/admin/meta/ads/forms/frm-4004", campaign: "World Rivers Day 2026", oldValue: "Draft", newValue: "Active", source: "Ads Manager" },
  { id: "act-14", at: "2026-08-31T23:59:00+05:30", user: "System", action: "Campaign completed", entityType: "Campaign", entityLabel: "Donate for a Cleaner Ganga", entityHref: "/admin/meta/ads/campaigns/cmp-1005", campaign: "Donate for a Cleaner Ganga", oldValue: "Active", newValue: "Completed", source: "Automation" },
  { id: "act-15", at: "2026-08-30T12:30:00+05:30", user: "Rohit Kumar", action: "Audience created", entityType: "Audience", entityLabel: "LAL 2% India - Donors", entityHref: "/admin/meta/ads/audiences?tab=lookalike", campaign: null, oldValue: null, newValue: "Lookalike 2% — India", source: "Ads Manager" },
];

/* ------------------------------------------------------------------ */
/* Assets & connections                                                */
/* ------------------------------------------------------------------ */

export const connectedAssets: ConnectedAsset[] = [
  { id: "ad-account", group: "Ad Account", name: "Namo Gange Official", handle: "INR · Asia/Kolkata", assetId: "act_123456789012345", connectedOn: "2026-05-02", permissions: ["ads_read", "ads_management", "business_management"], missingPermissions: [], lastSync: "2026-09-14T07:30:00+05:30", status: "Connected" },
  { id: "facebook-page", group: "Facebook Page", name: "Namo Gange", handle: "@namogange", assetId: "10987654321", connectedOn: "2026-05-02", permissions: ["pages_read_engagement", "pages_manage_ads"], missingPermissions: [], lastSync: "2026-09-14T07:30:00+05:30", status: "Connected" },
  { id: "instagram", group: "Instagram Business", name: "Namo Gange Trust", handle: "@namogangetrust", assetId: "17841400000000000", connectedOn: "2026-05-02", permissions: ["instagram_basic"], missingPermissions: ["instagram_manage_insights"], lastSync: "2026-09-12T22:40:00+05:30", status: "Needs Reauthorization" },
  { id: "pixel", group: "Pixel / Data Source", name: "Namo Gange Pixel", handle: "Website · namogange.org", assetId: "998877665544332", connectedOn: "2026-05-04", permissions: ["ads_management"], missingPermissions: [], lastSync: "2026-09-14T07:30:00+05:30", status: "Connected" },
  { id: "offline-events", group: "Pixel / Data Source", name: "Offline Conversions — Donations", handle: "Offline event set", assetId: "445566778899001", connectedOn: "2026-06-18", permissions: ["ads_management"], missingPermissions: [], lastSync: "2026-09-13T21:00:00+05:30", status: "Syncing" },
];

/* ------------------------------------------------------------------ */
/* Lookups & derived helpers                                           */
/* ------------------------------------------------------------------ */

export const getCampaign = (id: string) => campaigns.find((c) => c.id === id);
export const getAdSet = (id: string) => adSets.find((a) => a.id === id);
export const getAd = (id: string) => ads.find((a) => a.id === id);
export const getForm = (id: string) => instantForms.find((f) => f.id === id);
export const getLead = (id: string) => leads.find((l) => l.id === id);
export const getCreative = (id: string) => creatives.find((c) => c.id === id);

export const adSetsOfCampaign = (campaignId: string) =>
  adSets.filter((a) => a.campaignId === campaignId);
export const adsOfCampaign = (campaignId: string) =>
  ads.filter((a) => a.campaignId === campaignId);
export const adsOfAdSet = (adSetId: string) =>
  ads.filter((a) => a.adSetId === adSetId);
export const adsOfForm = (formId: string) =>
  ads.filter((a) => a.formId === formId);

export const campaignsOfForm = (formId: string): Campaign[] =>
  Array.from(new Set(adsOfForm(formId).map((a) => a.campaignId)))
    .map(getCampaign)
    .filter((c): c is Campaign => Boolean(c));

export const leadsOf = (
  filter: Partial<Pick<Lead, "campaignId" | "adSetId" | "adId" | "formId">>,
) =>
  leads.filter((l) =>
    Object.entries(filter).every(
      ([key, value]) => !value || l[key as keyof Lead] === value,
    ),
  );

export const sumMetrics = (rows: { metrics: Metrics }[]): Metrics =>
  rows.reduce<Metrics>(
    (total, row) => ({
      spend: total.spend + row.metrics.spend,
      impressions: total.impressions + row.metrics.impressions,
      reach: total.reach + row.metrics.reach,
      clicks: total.clicks + row.metrics.clicks,
      leads: total.leads + row.metrics.leads,
    }),
    { spend: 0, impressions: 0, reach: 0, clicks: 0, leads: 0 },
  );

/** 30-day daily series backing the trend charts. */
export const trendSeries = Array.from({ length: 30 }, (_, i) => {
  const day = new Date(Date.UTC(2026, 7, 16 + i));
  const wave = Math.sin(i / 3.2);
  return {
    date: day.toISOString().slice(0, 10),
    label: `${day.getUTCDate()} ${["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][day.getUTCMonth()]}`,
    spend: Math.round(32000 + i * 1100 + wave * 9000),
    leads: Math.round(38 + i * 1.6 + wave * 11),
    cpl: Math.round(108 - i * 1.2 + wave * 9),
    impressions: Math.round(18000 + i * 640 + wave * 4200),
    clicks: Math.round(520 + i * 22 + wave * 140),
  };
});
