"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Check, ExternalLink, KeyRound, Laptop, Lock, MoreHorizontal, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Sheet, SheetBody, SheetContent, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useTeam } from "../team-data/team-store";
import type { AccessLevel, ClientAccess, Member } from "../team-data/types";

const tabs = ["Overview", "Access", "Work", "Activity", "Security"] as const;
const clients = [{ id: "c-1", name: "Moksha Sewa" }, { id: "c-2", name: "CityCalls" }, { id: "c-3", name: "EnCodency" }];
const modules = ["CRM", "Campaigns", "Meta", "Instagram", "LinkedIn", "Google Business", "WhatsApp", "YouTube", "X", "Website", "SEO", "Automation", "Analytics", "Reports"];

export function MemberDetailPage({ memberId }: { memberId: string }) {
  const router = useRouter(); const { members, activity, isLoading, updateMember } = useTeam();
  const member = members.find((item) => item.id === memberId); const [tab, setTab] = useState<(typeof tabs)[number]>("Overview"); const [accessOpen, setAccessOpen] = useState(false); const [editing, setEditing] = useState<ClientAccess | null>(null); const [confirm, setConfirm] = useState<null | "suspend" | "sessions">(null);
  if (isLoading) return <div className="h-80 animate-pulse rounded-lg bg-[#F1F3F4]"/>;
  if (!member) return <div className="grid min-h-80 place-items-center text-center"><div><h2 className="font-semibold">Member not found</h2><Button asChild size="sm" className="mt-3"><Link href="/admin/team">Back to team</Link></Button></div></div>;
  const saveAccess = async (access: ClientAccess) => { await updateMember(member.id, { clientAccess: [...member.clientAccess.filter((item) => item.clientId !== access.clientId), access] }); setAccessOpen(false); setEditing(null); };
  return <div className="space-y-3">
    <Button variant="ghost" size="sm" onClick={() => router.back()}><ArrowLeft/>Back</Button>
    <section className="rounded-lg border border-[#E8EAED] bg-white p-4 shadow-[0_1px_2px_rgba(60,64,67,0.08)]"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-[#E8F0FE] font-medium text-[#1967D2] ring-1 ring-[#D2E3FC]">{member.name.split(" ").map((x) => x[0]).join("")}</span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-[18px] font-medium text-[#202124]">{member.name}</h2><Pill>{member.status}</Pill></div><p className="text-[12.5px] text-[#5F6368]">{member.email} · {member.jobTitle}</p><div className="mt-1 flex flex-wrap gap-3 text-[11px] text-[#5F6368]"><span>{member.roleName}</span><span>Joined {date(member.joinedAt)}</span><span>Active {relative(member.lastActiveAt)}</span><span>{member.clientAccess.length} clients</span><span>{member.groups.length} groups</span></div></div></div><div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => updateMember(member.id, { jobTitle: member.jobTitle === "Updated team member" ? "Team member" : "Updated team member" })}>Edit</Button><Button size="sm" variant={member.status === "suspended" ? "default" : "destructive"} onClick={() => member.status === "suspended" ? updateMember(member.id, { status: "active" }) : setConfirm("suspend")}>{member.status === "suspended" ? "Reactivate" : "Suspend"}</Button><Button size="icon-sm" variant="ghost"><MoreHorizontal/></Button></div></div></section>
    <div className="overflow-hidden rounded-lg border border-[#E8EAED] bg-white shadow-[0_1px_2px_rgba(60,64,67,0.08)]"><nav className="flex gap-0.5 overflow-x-auto border-b border-[#E8EAED] px-3">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-2.5 py-2.5 text-[12.5px] font-medium ${tab === item ? "border-[#1A73E8] text-[#1A73E8]" : "border-transparent text-[#5F6368] hover:text-[#202124]"}`}>{item}</button>)}</nav><div className="p-3 sm:p-4">
      {tab === "Overview" && <Overview member={member} activity={activity.filter((a) => a.memberId === member.id)} />}
      {tab === "Access" && <Access member={member} onGrant={() => { setEditing(null); setAccessOpen(true); }} onEdit={(a) => { setEditing(a); setAccessOpen(true); }} onRemove={(a) => updateMember(member.id, { clientAccess: member.clientAccess.filter((item) => item.clientId !== a.clientId) })} />}
      {tab === "Work" && <Work member={member} members={members} onReassign={(replacement) => { const target = members.find((m) => m.id === replacement); if (target) { updateMember(target.id, { ownedResources: [...target.ownedResources, ...member.ownedResources] }); updateMember(member.id, { ownedResources: [] }); } }} />}
      {tab === "Activity" && <ActivityTab member={member} items={activity.filter((a) => a.memberId === member.id)} />}
      {tab === "Security" && <Security member={member} onUpdate={(patch) => updateMember(member.id, patch)} onConfirm={setConfirm} />}
    </div></div>
    <AccessDrawer open={accessOpen} existing={editing} onOpen={setAccessOpen} onSave={saveAccess}/>
    <Dialog open={!!confirm} onOpenChange={(v) => !v && setConfirm(null)}><DialogContent><DialogHeader><DialogTitle>{confirm === "sessions" ? "Revoke all sessions" : `Suspend ${member.name}`}</DialogTitle><DialogDescription>{confirm === "sessions" ? "All devices will be signed out immediately." : "Access will be blocked. Owned resources remain protected and can be transferred before removal."}</DialogDescription></DialogHeader><DialogFooter><Button variant="ghost" onClick={() => setConfirm(null)}>Cancel</Button><Button variant="destructive" onClick={() => { updateMember(member.id, confirm === "sessions" ? { security: { ...member.security, activeSessions: 0 } } : { status: "suspended", security: { ...member.security, activeSessions: 0 } }); setConfirm(null); }}>Confirm</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function Overview({ member, activity }: { member: Member; activity: { id: string; action: string; entityName: string }[] }) { const blocks = [["Assigned role", member.roleName], ["Client access", member.clientAccess.map((a) => a.clientName).join(", ") || "No access"], ["Groups", member.groups.map((g) => g.name).join(", ") || "No groups"], ["Workload", `${member.workload.status} · ${member.workload.openTasks} open tasks`], ["Owned resources", member.ownedResources.map((r) => `${r.count} ${r.type.replaceAll("_", " ")}`).join(", ") || "No resources"], ["Recent activity", activity.slice(0, 2).map((a) => `${a.action}: ${a.entityName}`).join(" · ") || "No recent activity"]]; return <div className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{blocks.map(([title, value]) => <section key={title} className="min-h-24 rounded-lg border border-[#E8EAED] p-3.5"><h3 className="text-[11px] font-medium uppercase tracking-[0.04em] text-[#5F6368]">{title}</h3><p className="mt-2 text-[13px] font-medium capitalize text-[#202124]">{value}</p></section>)}</div>; }
function Access({ member, onGrant, onEdit, onRemove }: { member: Member; onGrant: () => void; onEdit: (a: ClientAccess) => void; onRemove: (a: ClientAccess) => void }) { return <><div className="mb-3 flex justify-between"><div><h3 className="text-sm font-semibold">Client access</h3><p className="text-xs text-slate-500">Explicit access grants and module restrictions.</p></div><Button size="sm" onClick={onGrant}>Grant client access</Button></div>{member.clientAccess.length ? <div className="overflow-x-auto rounded-sm border"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{["Client", "Access level", "Role override", "Modules", "Granted", "Actions"].map((x) => <th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{member.clientAccess.map((a) => <tr key={a.clientId}><td className="px-3 py-2.5 font-semibold">{a.clientName}</td><td className="px-3 py-2.5 capitalize">{a.accessLevel.replaceAll("_", " ")}</td><td className="px-3 py-2.5">{a.roleOverride || "Base role"}</td><td className="px-3 py-2.5">{(a.modules || []).slice(0, 3).join(", ") || "All modules"}{(a.modules?.length || 0) > 3 && ` +${a.modules!.length - 3}`}</td><td className="px-3 py-2.5">{date(a.grantedAt)}</td><td className="px-3 py-2.5"><Button size="sm" variant="ghost" onClick={() => onEdit(a)}>Edit</Button><Button size="sm" variant="ghost" className="text-red-600" onClick={() => onRemove(a)}>Remove</Button></td></tr>)}</tbody></table></div> : <Empty title="No client access" action={<Button size="sm" onClick={onGrant}>Grant access</Button>}/>}</>; }
function Work({ member, members, onReassign }: { member: Member; members: Member[]; onReassign: (id: string) => void }) { const [to, setTo] = useState(""); const stats = [["Open tasks", member.workload.openTasks], ["Overdue", member.workload.overdueTasks], ["Pending approvals", member.workload.pendingApprovals], ["Owned workflows", member.workload.workflows], ["Scheduled content", member.ownedResources.find((r) => r.type === "scheduled_post")?.count || 0]]; return <div className="space-y-3"><div className="grid grid-cols-2 gap-1 lg:grid-cols-5">{stats.map(([l, v]) => <div className="rounded-sm border p-3" key={l}><p className="text-[10px] text-slate-500">{l}</p><strong className="text-xl">{v}</strong></div>)}</div><section className="rounded-sm border"><div className="border-b px-3 py-2 text-xs font-semibold">Owned resources</div>{member.ownedResources.length ? member.ownedResources.map((r) => <div key={r.type} className="flex items-center justify-between border-b px-3 py-2 text-xs"><span className="capitalize">{r.type.replaceAll("_", " ")} · {r.count}</span><Button size="sm" variant="ghost"><ExternalLink/>View entity</Button></div>) : <Empty title="No owned resources"/>}<div className="flex gap-1 p-2"><select className="h-8 flex-1 rounded-sm border px-2 text-xs" value={to} onChange={(e) => setTo(e.target.value)}><option value="">Reassign all to…</option>{members.filter((m) => m.id !== member.id && m.status === "active").map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><Button size="sm" disabled={!to || !member.ownedResources.length} onClick={() => onReassign(to)}>Reassign</Button></div></section></div>; }
function ActivityTab({ items }: { member: Member; items: { id: string; action: string; entityName: string; module: string; clientName?: string; timestamp: string }[] }) { const [module, setModule] = useState("all"); const shown = items.filter((a) => module === "all" || a.module === module); return <div><div className="mb-2 flex gap-1"><select value={module} onChange={(e) => setModule(e.target.value)} className="h-8 rounded-sm border px-2 text-xs"><option value="all">All modules</option>{[...new Set(items.map((a) => a.module))].map((x) => <option key={x}>{x}</option>)}</select><Input type="date" className="h-8 w-auto text-xs"/></div>{shown.length ? <div className="divide-y rounded-sm border">{shown.map((a) => <div key={a.id} className="flex items-start justify-between gap-3 p-3 text-xs"><div><p><strong>{a.action}</strong> {a.entityName}</p><p className="mt-1 text-slate-500">{a.clientName || "Organization"} · {a.module} · {relative(a.timestamp)}</p></div><Button size="sm" variant="ghost"><ExternalLink/>Open entity</Button></div>)}</div> : <Empty title="No activity matches these filters"/>}</div>; }
function Security({ member, onUpdate, onConfirm }: { member: Member; onUpdate: (p: Partial<Member>) => void; onConfirm: (v: "sessions" | "suspend") => void }) { const rows = [[ShieldCheck, "Two-factor authentication", member.security.has2FA ? "Enabled" : "Not enabled", <Button key="2fa" size="sm" variant="outline" onClick={() => onUpdate({ security: { ...member.security, has2FA: true } })}>{member.security.has2FA ? "Required" : "Require 2FA"}</Button>], [Laptop, "Active sessions", `${member.security.activeSessions} signed-in devices`, <Button key="sessions" size="sm" variant="outline" disabled={!member.security.activeSessions} onClick={() => onConfirm("sessions")}>Revoke sessions</Button>], [KeyRound, "Password", `Last changed ${relative(member.security.passwordLastChanged)}`, <Button key="password" size="sm" variant="outline" onClick={() => onUpdate({ security: { ...member.security, passwordLastChanged: new Date(0).toISOString() } })}>Require reset</Button>], [Lock, "Last login", relative(member.security.lastLogin), <span key="last" className="text-xs text-slate-400">{member.security.lastLogin ? date(member.security.lastLogin) : "Never"}</span>], [UserRound, "Account status", member.status, <Button key="status" size="sm" variant="destructive" onClick={() => onConfirm("suspend")}>Suspend account</Button>]]; return <div className="divide-y rounded-sm border">{rows.map(([Icon, title, desc, action]) => { const I = Icon as typeof ShieldCheck; return <div key={String(title)} className="flex items-center gap-3 p-3"><I className="size-4 text-slate-500"/><div className="flex-1"><p className="text-xs font-semibold">{String(title)}</p><p className="text-[11px] capitalize text-slate-500">{String(desc)}</p></div>{action as React.ReactNode}</div>; })}</div>; }
function AccessDrawer({ open, existing, onOpen, onSave }: { open: boolean; existing: ClientAccess | null; onOpen: (v: boolean) => void; onSave: (a: ClientAccess) => void }) { const [clientId, setClient] = useState(existing?.clientId || "c-1"); const [level, setLevel] = useState<AccessLevel>(existing?.accessLevel || "full"); const [selected, setSelected] = useState<string[]>(existing?.modules || []); const activeClient = clients.find((c) => c.id === clientId)!; return <Sheet open={open} onOpenChange={onOpen}><SheetContent className="max-w-lg sm:max-w-lg"><SheetHeader><SheetTitle>{existing ? "Edit" : "Grant"} client access</SheetTitle></SheetHeader><SheetBody className="space-y-4"><Field title="Client"><select disabled={!!existing} value={clientId} onChange={(e) => setClient(e.target.value)} className="h-9 w-full rounded-sm border px-3 text-sm">{clients.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field title="Access level"><select value={level} onChange={(e) => setLevel(e.target.value as AccessLevel)} className="h-9 w-full rounded-sm border px-3 text-sm"><option value="full">Full client access</option><option value="module_restricted">Module restricted</option><option value="read_only">Read only</option></select></Field>{level === "module_restricted" && <Field title="Modules"><div className="grid grid-cols-2 gap-1">{modules.map((m) => <button key={m} onClick={() => setSelected(selected.includes(m) ? selected.filter((x) => x !== m) : [...selected, m])} className={`flex items-center gap-2 rounded-sm border p-2 text-xs ${selected.includes(m) ? "border-primary bg-primary/5 text-primary" : ""}`}><Check className={`size-3 ${selected.includes(m) ? "opacity-100" : "opacity-0"}`}/>{m}</button>)}</div></Field>}</SheetBody><SheetFooter><Button variant="ghost" onClick={() => onOpen(false)}>Cancel</Button><Button disabled={level === "module_restricted" && !selected.length} onClick={() => onSave({ clientId, clientName: activeClient.name, accessLevel: level, modules: level === "module_restricted" ? selected : undefined, grantedAt: existing?.grantedAt || new Date().toISOString() })}>Save access</Button></SheetFooter></SheetContent></Sheet>; }
function Field({ title, children }: { title: string; children: React.ReactNode }) { return <label className="block space-y-1.5 text-xs font-medium">{title}{children}</label>; }
function Empty({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="grid min-h-32 place-items-center text-center"><div><p className="mb-2 text-xs text-slate-500">{title}</p>{action}</div></div>; }
function Pill({ children }: { children: React.ReactNode }) { return <span className="rounded-md border border-[#E8EAED] bg-[#F1F3F4] px-1.5 py-0.5 text-[11px] font-medium capitalize text-[#3C4043]">{children}</span>; }
function relative(value: string | null) { if (!value) return "never"; const d = Math.max(0, Date.now() - new Date(value).getTime()); const hours = Math.round(d / 3600000); return hours < 24 ? `${hours}h ago` : `${Math.round(hours / 24)}d ago`; }
function date(value: string) { return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
