"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertTriangle, ChevronLeft, ChevronRight, ExternalLink, MoreHorizontal, Search, Shield, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Sheet, SheetBody, SheetContent, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Skeleton } from "@/components/ui/skeleton";
import { useTeam } from "../team-data/team-store";
import type { Member, MemberStatus } from "../team-data/types";

const statusStyle: Record<MemberStatus, string> = { active: "border-emerald-200 bg-emerald-50 text-emerald-700", invited: "border-blue-200 bg-blue-50 text-blue-700", suspended: "border-red-200 bg-red-50 text-red-700", deactivated: "border-slate-200 bg-slate-100 text-slate-600" };
const workStyle = { available: "text-emerald-700", normal: "text-blue-700", busy: "text-amber-700", overloaded: "text-red-700" };

export function MembersPage() {
  const { members, groups, invitations, activity, isLoading, error, refresh, updateMember, removeMember } = useTeam();
  const [query, setQuery] = useState(""); const [role, setRole] = useState("all"); const [status, setStatus] = useState("all"); const [group, setGroup] = useState("all"); const [client, setClient] = useState("all"); const [sort, setSort] = useState("name"); const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<string[]>([]); const [preview, setPreview] = useState<Member | null>(null); const [removeTarget, setRemoveTarget] = useState<Member | null>(null); const [removeStep, setRemoveStep] = useState(1); const [replacement, setReplacement] = useState("");
  const filtered = useMemo(() => members.filter((item) => `${item.name} ${item.email} ${item.jobTitle}`.toLowerCase().includes(query.toLowerCase()) && (role === "all" || item.roleId === role) && (status === "all" || item.status === status) && (group === "all" || item.groups.some((g) => g.id === group)) && (client === "all" || item.clientAccess.some((c) => c.clientId === client))).sort((a, b) => sort === "activity" ? String(b.lastActiveAt).localeCompare(String(a.lastActiveAt)) : sort === "workload" ? b.workload.openTasks - a.workload.openTasks : a.name.localeCompare(b.name)), [members, query, role, status, group, client, sort]);
  const pageItems = filtered.slice((page - 1) * 5, page * 5); const pages = Math.max(1, Math.ceil(filtered.length / 5));
  const clear = () => { setQuery(""); setRole("all"); setStatus("all"); setGroup("all"); setClient("all"); setSort("name"); setPage(1); };
  const patchSelected = async (patch: Partial<Member>) => { await Promise.all(selected.map((id) => updateMember(id, patch))); setSelected([]); };
  if (isLoading) return <Loading />;
  if (error) return <State title="Team data unavailable" detail="We couldn't load the workspace." action={<Button size="sm" onClick={refresh}>Retry</Button>} />;
  const kpis = [["Total members", members.length, "Organization seats"], ["Active members", members.filter((m) => m.status === "active").length, "Working now"], ["Pending invites", invitations.filter((i) => i.status === "pending").length, "Awaiting response"], ["Suspended", members.filter((m) => m.status === "suspended").length, "Access blocked"], ["Groups", groups.filter((g) => !g.archived).length, "Operational teams"], ["Seat usage", `${members.length}/25`, `${Math.round(members.length / 25 * 100)}% utilized`]];
  return <div className="space-y-3">
    <div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{kpis.map(([label, value, sub]) => <div key={label} className="rounded-lg border border-[#E8EAED] bg-white px-3.5 py-3 shadow-[0_1px_2px_rgba(60,64,67,0.08)]"><p className="text-[11.5px] font-medium text-[#5F6368]">{label}</p><div className="mt-1 flex items-end justify-between gap-2"><strong className="text-[20px] font-medium leading-6 text-[#202124]">{value}</strong><span className="truncate text-[11px] text-[#80868B]">{sub}</span></div></div>)}</div>
    <div className="overflow-hidden rounded-lg border border-[#E8EAED] bg-white shadow-[0_1px_2px_rgba(60,64,67,0.08)]">
      <div className="flex flex-wrap items-center gap-2 border-b border-[#E8EAED] p-2.5"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-[#80868B]" /><Input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} className="h-9 rounded-lg border-[#DADCE0] pl-8 text-[13px]" placeholder="Search name, email or title..." /></div><Select value={role} set={setRole} label="Role" options={uniq(members.map((m) => [m.roleId, m.roleName]))} /><Select value={client} set={setClient} label="Client" options={uniq(members.flatMap((m) => m.clientAccess.map((c) => [c.clientId, c.clientName])))} /><Select value={group} set={setGroup} label="Group" options={groups.map((g) => [g.id, g.name])} /><Select value={status} set={setStatus} label="Status" options={[["active", "Active"], ["invited", "Invited"], ["suspended", "Suspended"], ["deactivated", "Deactivated"]]} /><Select value={sort} set={setSort} label="Sort" allowAll={false} options={[["name", "Name"], ["activity", "Last active"], ["workload", "Workload"]]} /><Button size="sm" variant="ghost" onClick={clear}>Clear</Button></div>
      {selected.length > 0 && <div className="flex flex-wrap items-center gap-1 border-b bg-blue-50/70 px-3 py-2 text-xs"><strong className="mr-2 text-blue-900">{selected.length} selected</strong><Button size="sm" variant="outline" onClick={() => patchSelected({ roleId: "contributor", roleName: "Contributor" })}>Assign role</Button><Button size="sm" variant="outline" onClick={() => { const g = groups[0]; if (g) selected.forEach((id) => { const member = members.find((m) => m.id === id); if (member) updateMember(id, { groups: [...member.groups.filter((x) => x.id !== g.id), { id: g.id, name: g.name }] }); }); setSelected([]); }}>Add to group</Button><Button size="sm" variant="outline" onClick={() => patchSelected({ clientAccess: [{ clientId: "c-1", clientName: "Moksha Sewa", accessLevel: "full", grantedAt: new Date().toISOString() }] })}>Grant access</Button><Button size="sm" variant="outline" onClick={() => patchSelected({ clientAccess: [] })}>Remove access</Button><Button size="sm" variant="destructive" onClick={() => patchSelected({ status: "suspended" })}>Suspend</Button><Button size="sm" variant="ghost" onClick={() => setSelected([])}><X /></Button></div>}
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left text-[12.5px]"><thead className="bg-[#F8F9FA] text-[11px] uppercase tracking-[0.04em] text-[#5F6368]"><tr><th className="w-10 border-b border-[#E8EAED] px-3 py-2"><Checkbox checked={pageItems.length > 0 && pageItems.every((m) => selected.includes(m.id))} onCheckedChange={(yes) => setSelected(yes ? uniqStrings([...selected, ...pageItems.map((m) => m.id)]) : selected.filter((id) => !pageItems.some((m) => m.id === id)))} /></th>{["Member", "Role", "Groups", "Client access", "Workload", "Status", "Last active", ""].map((h) => <th key={h} className="border-b border-[#E8EAED] px-3 py-2 font-medium">{h}</th>)}</tr></thead><tbody>{pageItems.map((member) => <tr key={member.id} onClick={() => setPreview(member)} className={`cursor-pointer transition hover:bg-[#F8F9FA] ${selected.includes(member.id) ? "bg-[#F8FBFF]" : ""}`}><td className="border-b border-[#F1F3F4] px-3 py-2.5" onClick={(e) => e.stopPropagation()}><Checkbox checked={selected.includes(member.id)} onCheckedChange={(yes) => setSelected(yes ? [...selected, member.id] : selected.filter((id) => id !== member.id))} /></td><td className="border-b border-[#F1F3F4] px-3 py-2"><Identity member={member} /></td><td className="border-b border-[#F1F3F4] px-3 py-2"><Link onClick={(e) => e.stopPropagation()} href={roleHref(member.roleId, member.roleName)} className="font-medium text-[#3C4043] hover:text-[#1A73E8]">{member.roleName}</Link></td><td className="border-b border-[#F1F3F4] px-3 py-2"><Chips values={member.groups.map((g) => g.name)} /></td><td className="border-b border-[#F1F3F4] px-3 py-2"><Chips values={member.clientAccess.map((c) => c.clientName)} empty="No access" /></td><td className="border-b border-[#F1F3F4] px-3 py-2"><span className={`font-medium capitalize ${workStyle[member.workload.status]}`}>{member.workload.status}</span><p className="text-[11px] text-[#80868B]">{member.workload.openTasks} tasks · {member.workload.pendingApprovals} approvals</p></td><td className="border-b border-[#F1F3F4] px-3 py-2"><Status value={member.status} /></td><td className="border-b border-[#F1F3F4] px-3 py-2 text-[#5F6368]">{relative(member.lastActiveAt)}</td><td className="border-b border-[#F1F3F4] px-3 py-2" onClick={(e) => e.stopPropagation()}><MemberMenu member={member} onPreview={() => setPreview(member)} onPatch={(p) => updateMember(member.id, p)} onRemove={() => { setRemoveTarget(member); setRemoveStep(1); }} /></td></tr>)}</tbody></table></div>
      <div className="divide-y md:hidden">{pageItems.map((member) => <button key={member.id} onClick={() => setPreview(member)} className="w-full p-3 text-left hover:bg-slate-50"><div className="flex items-start justify-between"><Identity member={member} /><Status value={member.status} /></div><div className="mt-2 flex items-center justify-between text-[11px] text-slate-500"><span>{member.roleName}</span><span className={`capitalize ${workStyle[member.workload.status]}`}>{member.workload.status} · {member.workload.openTasks} tasks</span></div></button>)}</div>
      {pageItems.length === 0 && <State title={query ? "No search results" : "No members match these filters"} detail="Clear filters or invite a new member." action={<Button size="sm" variant="outline" onClick={clear}>Clear filters</Button>} />}
      <div className="flex items-center justify-between border-t px-3 py-2 text-xs text-slate-500"><span>{filtered.length} members · page {page} of {pages}</span><div className="flex gap-1"><Button size="icon-sm" variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}><ChevronLeft /></Button><Button size="icon-sm" variant="outline" disabled={page === pages} onClick={() => setPage(page + 1)}><ChevronRight /></Button></div></div>
    </div>
    <div className="grid gap-1 lg:grid-cols-3"><Support title="Recent team activity" action={<Link className="text-xs font-medium text-primary" href="/admin/team/activity">View all</Link>}>{activity.slice(0, 4).map((a) => <p key={a.id} className="border-t py-2 text-xs"><strong>{a.memberName}</strong> {a.action.toLowerCase()} <span className="text-slate-500">{a.entityName}</span></p>)}</Support><Support title="Needs attention">{([[`${invitations.filter((i) => i.status === "pending").length} invitations pending`, "/admin/team/invitations"], [`${members.filter((m) => !m.security.has2FA && m.status === "active").length} active members without 2FA`, "/admin/team/activity"], [`${members.filter((m) => m.workload.status === "overloaded").length} overloaded members`, "/admin/team?status=active"]] as [string, string][]).map(([t, h]) => <Link key={t} href={h} className="flex items-center justify-between border-t py-2 text-xs hover:text-primary"><span>{t}</span><ExternalLink className="size-3" /></Link>)}</Support><Support title="Workload overview">{["available", "normal", "busy", "overloaded"].map((s) => <div key={s} className="flex items-center justify-between border-t py-2 text-xs"><span className={`capitalize ${workStyle[s as keyof typeof workStyle]}`}>{s}</span><strong>{members.filter((m) => m.workload.status === s).length}</strong></div>)}</Support></div>
    <MemberPreview member={preview && members.find((m) => m.id === preview.id) || null} open={!!preview} onOpen={setPreview} onPatch={updateMember} />
    <RemoveFlow member={removeTarget} step={removeStep} setStep={setRemoveStep} replacement={replacement} setReplacement={setReplacement} members={members} onClose={() => setRemoveTarget(null)} onConfirm={async () => { if (removeTarget) await removeMember(removeTarget.id, replacement || undefined); setRemoveTarget(null); }} />
  </div>;
}

function MemberMenu({ member, onPreview, onPatch, onRemove }: { member: Member; onPreview: () => void; onPatch: (p: Partial<Member>) => void; onRemove: () => void }) { const router = useRouter(); return <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon-sm" variant="ghost"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={onPreview}>Quick preview</DropdownMenuItem><DropdownMenuItem onSelect={() => router.push(`/admin/team/${member.id}`)}>View profile</DropdownMenuItem><DropdownMenuItem onSelect={() => onPatch({ roleId: "contributor", roleName: "Contributor" })}>Change role to Contributor</DropdownMenuItem><DropdownMenuItem onSelect={() => onPatch({ clientAccess: [{ clientId: "c-1", clientName: "Moksha Sewa", accessLevel: "full", grantedAt: new Date().toISOString() }] })}>Grant Moksha Sewa access</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onSelect={() => onPatch({ status: member.status === "suspended" ? "active" : "suspended" })} variant={member.status === "suspended" ? "default" : "destructive"}>{member.status === "suspended" ? "Reactivate" : "Suspend"}</DropdownMenuItem><DropdownMenuItem onSelect={() => onPatch({ status: "deactivated" })} variant="destructive">Deactivate</DropdownMenuItem><DropdownMenuItem onSelect={onRemove} variant="destructive">Remove member</DropdownMenuItem></DropdownMenuContent></DropdownMenu>; }

function MemberPreview({ member, open, onOpen, onPatch }: { member: Member | null; open: boolean; onOpen: (m: Member | null) => void; onPatch: (id: string, p: Partial<Member>) => Promise<void> }) { return <Sheet open={open} onOpenChange={(v) => !v && onOpen(null)}><SheetContent className="max-w-lg sm:max-w-lg">{member && <><SheetHeader><SheetTitle>Member preview</SheetTitle></SheetHeader><SheetBody><div className="flex items-center gap-3 border-b pb-4"><Avatar name={member.name} large /><div><h2 className="font-semibold">{member.name}</h2><p className="text-xs text-slate-500">{member.email}</p><p className="text-xs text-slate-500">{member.jobTitle}</p></div></div><Section title="Role & status"><div className="flex items-center justify-between"><Link href={roleHref(member.roleId, member.roleName)} className="text-sm font-medium text-primary">{member.roleName}</Link><Status value={member.status} /></div></Section><Section title="Client access"><Chips values={member.clientAccess.map((c) => c.clientName)} empty="No client access" /></Section><Section title="Groups"><Chips values={member.groups.map((g) => g.name)} empty="No groups" /></Section><Section title="Workload"><p className="text-sm"><strong>{member.workload.openTasks}</strong> open tasks · {member.workload.overdueTasks} overdue · {member.workload.pendingApprovals} approvals</p></Section><Section title="Owned resources"><p className="text-sm">{member.ownedResources.map((r) => `${r.count} ${r.type.replaceAll("_", " ")}`).join(" · ") || "No owned resources"}</p></Section><Section title="Security summary"><div className="flex items-center gap-2 text-sm"><Shield className="size-4" />2FA {member.security.has2FA ? "enabled" : "not enabled"} · {member.security.activeSessions} sessions</div></Section></SheetBody><SheetFooter><Button variant="outline" onClick={() => onPatch(member.id, { status: member.status === "suspended" ? "active" : "suspended" })}>{member.status === "suspended" ? "Reactivate" : "Suspend"}</Button><Button asChild><Link href={`/admin/team/${member.id}`}>View full profile</Link></Button></SheetFooter></>}</SheetContent></Sheet>; }

function RemoveFlow({ member, step, setStep, replacement, setReplacement, members, onClose, onConfirm }: { member: Member | null; step: number; setStep: (n: number) => void; replacement: string; setReplacement: (s: string) => void; members: Member[]; onClose: () => void; onConfirm: () => void }) { const total = member?.ownedResources.reduce((n, r) => n + r.count, 0) ?? 0; return <Dialog open={!!member} onOpenChange={(v) => !v && onClose()}><DialogContent><DialogHeader><DialogTitle>Remove {member?.name}</DialogTitle><DialogDescription>Step {step} of 3 · This guided flow prevents orphaned work.</DialogDescription></DialogHeader>{step === 1 && <div className="rounded-sm border border-amber-200 bg-amber-50 p-3 text-sm"><div className="flex gap-2"><AlertTriangle className="size-4 text-amber-700" /><span><strong>Impact summary</strong><br />{total} owned resources, {member?.clientAccess.length} client assignments and {member?.groups.length} group memberships will be affected.</span></div></div>}{step === 2 && <div className="space-y-2"><label className="text-xs font-medium">Replacement member</label><select className="h-9 w-full rounded-sm border px-3 text-sm" value={replacement} onChange={(e) => setReplacement(e.target.value)}><option value="">Select replacement</option>{members.filter((m) => m.id !== member?.id && m.status === "active").map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><p className="text-xs text-slate-500">All tasks, campaigns, workflows, reports and scheduled content will transfer.</p></div>}{step === 3 && <div className="rounded-sm border p-3 text-sm"><strong>Confirm removal</strong><p className="mt-1 text-slate-500">Ownership will transfer, client access and group membership will be removed, and all sessions revoked.</p></div>}<DialogFooter><Button variant="ghost" onClick={step === 1 ? onClose : () => setStep(step - 1)}>{step === 1 ? "Cancel" : "Back"}</Button><Button variant={step === 3 ? "destructive" : "default"} disabled={step === 2 && total > 0 && !replacement} onClick={step === 3 ? onConfirm : () => setStep(step + 1)}>{step === 3 ? "Remove member" : "Continue"}</Button></DialogFooter></DialogContent></Dialog>; }

function Identity({ member }: { member: Member }) { return <div className="flex items-center gap-2.5"><Avatar name={member.name} /><div className="min-w-0"><p className="font-medium text-[#202124]">{member.name}</p><p className="max-w-[220px] truncate text-[11px] text-[#5F6368]">{member.email} · {member.jobTitle}</p></div></div>; }
function Avatar({ name, large = false }: { name: string; large?: boolean }) { return <span className={`grid shrink-0 place-items-center rounded-full bg-slate-900 font-semibold text-white ${large ? "size-11 text-sm" : "size-7 text-[10px]"}`}>{name.split(" ").map((x) => x[0]).slice(0, 2).join("")}</span>; }
function Status({ value }: { value: MemberStatus }) { return <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-semibold capitalize ${statusStyle[value]}`}>{value}</span>; }
function Chips({ values, empty = "—" }: { values: string[]; empty?: string }) { if (!values.length) return <span className="text-[11px] text-slate-400">{empty}</span>; return <div className="flex items-center gap-1"><span className="max-w-[100px] truncate rounded-sm bg-slate-100 px-1.5 py-0.5 text-[10px] font-medium">{values[0]}</span>{values.length > 1 && <span className="text-[10px] text-slate-500">+{values.length - 1}</span>}</div>; }
function Select({ value, set, label, options, allowAll = true }: { value: string; set: (v: string) => void; label: string; options: string[][]; allowAll?: boolean }) { return <select aria-label={label} value={value} onChange={(e) => set(e.target.value)} className="h-9 max-w-[150px] rounded-lg border border-[#DADCE0] bg-white px-2.5 text-[12px] text-[#3C4043] outline-none focus:border-[#1A73E8] focus:ring-[3px] focus:ring-[#1A73E8]/15">{allowAll && <option value="all">{label}: All</option>}{options.map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select>; }
function Support({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-lg border border-[#E8EAED] bg-white p-3.5 shadow-[0_1px_2px_rgba(60,64,67,0.08)]"><div className="mb-1 flex items-center justify-between"><h3 className="text-[13px] font-medium text-[#202124]">{title}</h3>{action}</div>{children}</section>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-b py-4"><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-slate-500">{title}</h3>{children}</section>; }
function State({ title, detail, action }: { title: string; detail: string; action?: React.ReactNode }) { return <div className="grid min-h-48 place-items-center p-6 text-center"><div><Users className="mx-auto size-7 text-slate-300" /><h3 className="mt-2 text-sm font-semibold">{title}</h3><p className="mb-3 mt-1 text-xs text-slate-500">{detail}</p>{action}</div></div>; }
function Loading() { return <div className="space-y-2"><div className="grid grid-cols-3 gap-1 lg:grid-cols-6">{Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-16" />)}</div><Skeleton className="h-10" /><Skeleton className="h-80" /></div>; }
function relative(date: string | null) { if (!date) return "Never"; const hours = Math.round((Date.now() - new Date(date).getTime()) / 3600000); return hours < 1 ? "Just now" : hours < 24 ? `${hours}h ago` : `${Math.round(hours / 24)}d ago`; }
function uniq(items: string[][]) { return [...new Map(items.map((x) => [x[0], x])).values()]; }
function uniqStrings(items: string[]) { return [...new Set(items)]; }
function roleHref(roleId: string, roleName: string) { const known: Record<string, string> = { owner: "organization-owner", admin: "organization-admin", contributor: "content-writer", viewer: "viewer", analyst: "analyst" }; return `/admin/roles/${known[roleId] || roleName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`; }
