"use client";
import { useState } from "react";
import { BarChart3, Download, FileText, Plus, Settings, ShieldCheck, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { AdminPageTitle } from "../shared/admin-page-title";
import { ChannelLogo } from "../shared/channel-logo";
import { cn } from "@/lib/utils/cn";
type View = "analytics" | "reports" | "team" | "roles" | "integrations" | "billing" | "settings";
const team = [{ name: "Manish Sirohi", email: "manishsirohi@encodency.com", role: "Organization Admin", Clients: "Moksha Sewa", status: "Active" }, { name: "Priya Sharma", email: "priya@namogange.org", role: "Marketing Manager", Clients: "Moksha Sewa", status: "Active" }, { name: "Amit Singh", email: "amit@namogange.org", role: "Social Media Manager", Clients: "Moksha Sewa", status: "Active" }, { name: "Neha Verma", email: "neha@namogange.org", role: "SEO Manager", Clients: "Moksha Sewa", status: "Invited" }];
const roles = ["Organization Owner", "Organization Admin", "Project Admin", "Marketing Manager", "Social Media Manager", "SEO Manager", "Ads Manager", "Sales Agent", "Content Writer", "Analyst", "Viewer"];
const integrations = ["Meta & Instagram", "LinkedIn", "Google Business", "WhatsApp", "YouTube", "Search Console", "Website"];
export function AdminManagementPage({ view }: { view: View }) { const titles = { analytics: "Analytics", reports: "Reports", team: "Team", roles: "Roles & Permissions", integrations: "Integrations", billing: "Billing", settings: "Settings" }; const title = titles[view]; return <div className="space-y-3"><AdminPageTitle eyebrow={`Management / ${title}`} title={title} description={`${title} for Namo Gange Trust and Moksha Sewa.`} action={(view === "team" || view === "roles") ? <button className="flex h-8 items-center gap-1 rounded-lg bg-[#EB0711] px-3 text-[8.5px] font-semibold text-white"><Plus className="size-3.5" />{view === "team" ? "Invite Member" : "Create Role"}</button> : undefined} />{view === "analytics" && <Analytics />}{view === "reports" && <Reports />}{view === "team" && <Team />}{view === "roles" && <Roles />}{view === "integrations" && <Integrations />}{view === "billing" && <Billing />}{view === "settings" && <SettingsPage />}</div> }
function Analytics() { const metrics = [["Reach", "174.6K"], ["Impressions", "426.8K"], ["Clicks", "18.2K"], ["Leads", "426"], ["Conversions", "109"], ["ROAS", "4.8x"]]; return <><div className="flex flex-wrap gap-2 rounded-lg border border-[#DDE4ED] bg-white p-2 shadow-sm">{["Moksha Sewa", "Last 30 days", "All channels", "All campaigns"].map(x => <button key={x} className="h-8 rounded-md border border-[#DDE4ED] px-3 text-[8px] font-semibold text-[#425273]">{x}⌄</button>)}</div><div className="grid grid-cols-2 gap-2 lg:grid-cols-6">{metrics.map(([l, v]) => <Stat key={l} label={l} value={v} />)}</div><div className="grid gap-3 lg:grid-cols-[1.3fr_.7fr]"><Panel title="Performance over time"><div className="flex h-52 items-end gap-3 px-5 pb-4">{[68, 82, 76, 108, 96, 126, 118, 148, 139, 166, 158, 184].map((h, i) => <span key={i} className="flex-1 rounded-t bg-gradient-to-t from-[#EB0711] to-[#F6A1A7]" style={{ height: h }} />)}</div></Panel><Panel title="Channel contribution">{[["Meta & Instagram", "46%"], ["Google Business", "18%"], ["WhatsApp", "16%"], ["LinkedIn", "11%"], ["YouTube", "9%"]].map(([c, v]) => <div key={c} className="flex items-center gap-2 border-b border-[#E8EDF3] p-3"><ChannelLogo channel={c} className="size-6" /><span className="flex-1 text-[8.5px] font-semibold">{c}</span><strong className="text-[9px]">{v}</strong></div>)}</Panel></div></> }
function Reports() { const [generated, setGenerated] = useState(false); return <div className="grid gap-3 lg:grid-cols-[.75fr_1.25fr]"><Panel title="Generate report"><div className="space-y-3 p-4">{["Project: Moksha Sewa", "Date range: Last 30 days", "Channels: All connected", "Sections: SEO, CRM, Campaigns"].map(x => <button key={x} className="flex h-9 w-full items-center justify-between rounded-lg border border-[#DDE4ED] px-3 text-left text-[8.5px] font-medium">{x}<span>⌄</span></button>)}<div className="flex gap-2">{["PDF", "CSV", "Excel"].map(x => <button key={x} className="flex-1 rounded-lg border border-[#DDE4ED] py-2 text-[8px] font-semibold">{x}</button>)}</div><button onClick={() => { setGenerated(true); toast.success("Report generated successfully") }} className="h-9 w-full rounded-lg bg-[#EB0711] text-[8.5px] font-semibold text-white"><Sparkles className="mr-1 inline size-3" />Generate Report</button>{generated && <p className="text-center text-[8px] font-semibold text-[#078359]">Report is ready to download.</p>}</div></Panel><Panel title="Recent reports">{["August Marketing Report", "SEO Performance – August", "Campaign Summary Q3", "Lead Attribution Report"].map((r, i) => <div key={r} className="flex items-center gap-3 border-b border-[#E8EDF3] p-3"><FileText className="size-5 text-[#EB0711]" /><div className="flex-1"><p className="text-[8.5px] font-bold">{r}</p><p className="text-[7px] text-[#75829D]">Generated {i + 1} week ago · PDF</p></div><Download className="size-3.5" /></div>)}</Panel></div> }
function Team() { return <Panel title="Organization members"><Table headers={["Member", "Role", "Clients", "Status", "Last Login"]} rows={team.map((m, i) => [`${m.name}\n${m.email}`, m.role, m.Clients, m.status, i ? `${i} days ago` : "Today"])} /></Panel> }
function Roles() { return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{roles.map((role, i) => <div key={role} className="rounded-lg border border-[#DDE4ED] bg-white p-3 shadow-sm"><div className="flex items-start gap-2"><span className="grid size-8 place-items-center rounded-lg bg-[#FFF0F1] text-[#EB0711]"><ShieldCheck className="size-4" /></span><div className="flex-1"><p className="text-[9px] font-bold">{role}</p><p className="text-[7.5px] text-[#75829D]">{i < 2 ? "Full organization access" : "Scoped module permissions"}</p></div><span className="text-[7px] text-[#687797]">{Math.max(0, 4 - i)} users</span></div><div className="mt-3 flex flex-wrap gap-1">{["Analytics", "Publishing", "CRM", "SEO"].slice(0, i < 2 ? 4 : 2).map(p => <span key={p} className="rounded bg-[#F1F4F8] px-1.5 py-1 text-[6.5px]">{p}</span>)}</div></div>)}</div> }
function Integrations() { return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{integrations.map((item, i) => <div key={item} className="rounded-lg border border-[#DDE4ED] bg-white p-3 shadow-sm"><div className="flex items-center gap-3"><ChannelLogo channel={item} className="size-9" /><div className="flex-1"><p className="text-[9px] font-bold">{item}</p><p className="text-[7px] text-[#75829D]">Moksha Sewa account</p></div><span className={cn("rounded-full px-2 py-1 text-[7px] font-semibold", i === 1 ? "bg-[#FFE8EA] text-[#D91521]" : "bg-[#E5F7EF] text-[#078359]")}>{i === 1 ? "Expiring" : "Connected"}</span></div><div className="mt-3 flex items-center justify-between border-t border-[#E8EDF3] pt-2 text-[7px] text-[#75829D]"><span>Last sync: {i + 1} hours ago</span><button className="font-semibold text-[#EB0711]">{i === 1 ? "Reconnect" : "Sync"}</button></div></div>)}</div> }
function Billing() { return <div className="grid gap-3 lg:grid-cols-[1fr_.8fr]"><Panel title="Current plan"><div className="p-4"><span className="rounded-full bg-[#FFF0F1] px-2 py-1 text-[7px] font-bold text-[#EB0711]">GROWTH PLAN</span><p className="mt-3 text-[24px] font-bold">₹12,999 <small className="text-[9px] font-normal text-[#75829D]">/ month</small></p><p className="mt-1 text-[8px] text-[#75829D]">Renews on 15 October 2026</p><button className="mt-4 h-8 rounded-lg bg-[#EB0711] px-4 text-[8px] font-semibold text-white">Upgrade Plan</button></div></Panel><Panel title="Usage"><div className="space-y-4 p-4">{[["Clients", "1 of 5", 20], ["Team members", "4 of 15", 27], ["Connected channels", "7 of 20", 35], ["AI credits", "6,420 of 10,000", 64]].map(([l, v, p]) => <div key={String(l)}><div className="flex justify-between text-[8px]"><span>{l}</span><strong>{v}</strong></div><div className="mt-1 h-1.5 rounded-full bg-[#E9EDF3]"><div className="h-full rounded-full bg-[#EB0711]" style={{ width: `${p}%` }} /></div></div>)}</div></Panel><Panel title="Invoices"><Table headers={["Invoice", "Date", "Amount", "Status"]} rows={[["INV-2026-009", "15 Sep 2026", "₹12,999", "Paid"], ["INV-2026-008", "15 Aug 2026", "₹12,999", "Paid"], ["INV-2026-007", "15 Jul 2026", "₹12,999", "Paid"]]} /></Panel></div> }
function SettingsPage() { const [tab, setTab] = useState("Organization"); const tabs = ["Organization", "Clients", "Branding", "Notifications", "Integrations", "Security", "Preferences"]; return <div className="grid gap-3 lg:grid-cols-[190px_1fr]"><nav className="rounded-lg border border-[#DDE4ED] bg-white p-2 shadow-sm">{tabs.map(t => <button key={t} onClick={() => setTab(t)} className={cn("flex h-9 w-full items-center gap-2 rounded-md px-2.5 text-[8.5px] font-semibold", tab === t ? "bg-[#FFF0F1] text-[#EB0711]" : "text-[#5E6D89]")}><Settings className="size-3.5" />{t}</button>)}</nav><Panel title={tab}><div className="grid gap-3 p-4 sm:grid-cols-2">{[["Organization name", "Namo Gange Trust"], ["Primary project", "Moksha Sewa"], ["Timezone", "Asia/Kolkata"], ["Default language", "English"], ["Contact email", "manishsirohi@encodency.com"], ["Phone", "+91 98765 43210"]].map(([l, v]) => <label key={l} className="text-[8px] font-semibold text-[#566582]">{l}<input defaultValue={v} className="mt-1 h-9 w-full rounded-lg border border-[#DDE4ED] px-3 text-[8.5px] font-normal outline-none focus:border-[#EB777E]" /></label>)}<button onClick={() => toast.success("Settings saved")} className="h-9 rounded-lg bg-[#EB0711] text-[8.5px] font-semibold text-white sm:col-span-2 sm:w-32">Save changes</button></div></Panel></div> }
function Stat({ label = "Metric", value = "—" }: { label?: string; value?: string }) { return <div className="rounded-lg border border-[#DDE4ED] bg-white p-2.5 shadow-sm"><BarChart3 className="size-3.5 text-[#EB0711]" /><p className="mt-1.5 text-[7px] text-[#75829D]">{label}</p><p className="text-[16px] font-bold">{value}</p></div> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-lg border border-[#DDE4ED] bg-white shadow-sm"><h2 className="border-b border-[#E8EDF3] px-3 py-2.5 text-[9.5px] font-bold">{title}</h2>{children}</section> }
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead className="bg-[#F8FAFD] text-[7px] uppercase text-[#75829D]"><tr>{headers.map(h => <th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#E8EDF3]">{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j} className="whitespace-pre-line px-3 py-2.5 text-[8.5px] text-[#354568]">{cell}</td>)}</tr>)}</tbody></table></div> }
